consensus-engine/src/lib.rs, consensus-engine/src/overlay/flat_overlay.rs, consensus-engine/tests/fuzz/sut.rs, simulations/config/carnot.json, simulations/src/bin/app/main.rs, simulations/src/bin/app/overlay_node.rs, simulations/src/node/carnot/mod.rs, simulations/src/output_processors/mod.rs, simulations/src/runner/async_runner.rs, simulations/src/runner/glauber_runner.rs, simulations/src/runner/layered_runner.rs, simulations/src/runner/mod.rs, simulations/src/runner/sync_runner.rs, simulations/src/settings.rs, simulations/src/streaming/io.rs, simulations/src/streaming/naive.rs, simulations/src/streaming/runtime_subscriber.rs, simulations/src/streaming/settings_subscriber.rs, simulations/src/warding/minmax.rs, simulations/src/warding/mod.rs, simulations/src/warding/stalled.rs, simulations/src/warding/ttf.rs, tests/src/nodes/nomos.rs
~~Skipped leader selection settings (using RoundRobin atm), but the addition would look similar to this.~~
Updated simulation runner to be dynamic dispatch when interacting with nodes.
=> Tree settings for sim overlay

simulations/src/node/carnot/mod.rs, simulations/src/node/dummy.rs, simulations/src/node/dummy_streaming.rs, simulations/src/node/mod.rs, simulations/src/runner/sync_runner.rs, simulations/src/streaming/io.rs, simulations/src/streaming/naive.rs, simulations/src/streaming/runtime_subscriber.rs, simulations/src/streaming/settings_subscriber.rs, simulations/src/warding/minmax.rs, simulations/src/warding/stalled.rs, simulations/src/warding/ttf.rs
Fix #255, make `Node` trait `current_view` return `View` struct.
=> Change simulation `Node` trait `current_view` method return `View`

simulations/config/carnot.json, simulations/src/node/carnot/mod.rs
Add option to gather node id alongside the node state.
=> Simulations nodeid report

nomos-services/consensus/src/network/adapters/libp2p.rs
Based on the PR #279 
Added missing message handlings.
=> Handle all message types received via gossipsub

nomos-libp2p/src/lib.rs, nomos-services/network/src/backends/libp2p.rs
=> Check if topic is being subscribed before self-notification

consensus-engine/src/lib.rs, consensus-engine/src/overlay/flat_overlay.rs, consensus-engine/src/overlay/leadership.rs, consensus-engine/src/overlay/membership.rs, consensus-engine/src/overlay/mod.rs, consensus-engine/src/overlay/random_beacon.rs, consensus-engine/src/overlay/tree_overlay/overlay.rs, consensus-engine/tests/fuzz/sut.rs, nodes/nomos-node/src/lib.rs, nomos-services/consensus/src/committee_membership/mod.rs, nomos-services/consensus/src/leader_selection/mod.rs, nomos-services/consensus/src/lib.rs, simulations/src/bin/app/overlay_node.rs, simulations/src/node/carnot/mod.rs
I replicated the same abstraction for `LeaderSelection` for updating the committees.
This also superseed #265 .
=> Add update committees structure for overlay

simulations/src/bin/app/main.rs, simulations/src/network/mod.rs
Initialize nodes using `par_iter`.
=> Parallel node init

simulations/src/node/carnot/event_builder.rs, simulations/src/node/carnot/mod.rs, simulations/src/node/carnot/tally.rs
=> Simulation prune tally

consensus-engine/src/lib.rs, consensus-engine/src/overlay/flat_overlay.rs, consensus-engine/src/overlay/mod.rs, consensus-engine/src/overlay/tree_overlay/overlay.rs, simulations/src/node/carnot/mod.rs
Update overlay in simulation node.
Also remove unused `rebuild` method in overlay.
=> Sim update overlay

Cargo.toml, nomos-da-core/reed-solomon/Cargo.toml, nomos-da-core/reed-solomon/src/lib.rs
First iteration over reed solomon encoding/decoding. Tried to simplify the API. This may be due to change in the future whenever we have to mix it with the commitments.
=> RS encoding/decoding base methods

mixnet/client/src/config.rs, mixnet/client/src/receiver.rs, mixnet/node/src/client_notifier.rs, mixnet/node/src/config.rs, mixnet/node/src/lib.rs, mixnet/protocol/src/lib.rs, tests/src/tests/mixnet.rs
As described in https://github.com/logos-co/nomos-node/pull/307#discussion_r1298982429, I made mixnode listen connections from mixclient (Previously, mixclient has opened a port listening connections from mixnode).
=> make mixnode listen conns from mixclient

nomos-da-core/kzg/Cargo.toml, nomos-da-core/kzg/benches/nomos_kzg.rs, nomos-da-core/kzg/src/dynamic_kzg.rs, nomos-da-core/kzg/src/lib.rs, nomos-da-core/kzg/src/types.rs
* Extract and refactor library methods to use custom elements per blob
* Added benches
=> DA kzg custom blob sizes

Cargo.toml, nomos-da-core/kzg/Cargo.toml, nomos-da-core/kzg/benches/nomos_kzg.rs, nomos-da-core/kzg/src/dynamic_kzg.rs, nomos-da-core/kzg/src/lib.rs, nomos-da-core/kzg/src/types.rs
Wrapping methods over a library. Still need to be tested against RS and figure out how do they work together to adapt both wrapper to work together. But it is a first naive starting point.
=> DA kzg initial approach

nomos-da-core/kzg/benches/nomos_kzg.rs, nomos-da-core/kzg/src/lib.rs
Bench wasn't updated to latest changes, making CI and build to fail.
=> Fix kzg bench

nodes/mixnode/src/lib.rs, nodes/mixnode/src/main.rs, tests/Cargo.toml, tests/src/nodes/mixnode.rs, tests/src/nodes/mod.rs
https://github.com/logos-co/nomos-node/pull/339#issuecomment-1698718343
=> Fix tests for the overwatch mixnode

.github/workflows/codecov.yml
The same github action I've used in waku-bindings. Might require repo owner to register on codecov.io
=> GH Actions: Codecov

nomos-services/data-availability/Cargo.toml, nomos-services/data-availability/src/network/adapters/libp2p.rs
* Fixed tracing import error
* Fixed nomos network libp2p feature
Open question **How could this even worked before?**
=> Da service compiling fixes

.codecov.yml, .github/workflows/codecov.yml
Config to disable Codecov annotations.
=> Disable codecov annotations

nodes/nomos-node/src/lib.rs, nomos-core/src/block/builder.rs, nomos-core/src/da/blob/mod.rs, nomos-core/src/da/blob/select.rs, nomos-core/src/da/mod.rs, nomos-core/src/tx/mod.rs, nomos-core/src/tx/select.rs, nomos-services/consensus/src/lib.rs, tests/src/nodes/nomos.rs
For now just transactions are being pulled. `"Blob"` Selection is not plugged still, just adds an empty set of them.
At the moment there is a mess about what a blob is and what do we need to include in the block. We will solve those issues in further PRs. They actually imply changing a bit more of the generics and it bounds.
=> Pipe propose block

nodes/nomos-node/src/lib.rs, nomos-core/src/block/builder.rs, nomos-core/src/da/blob/mod.rs, nomos-core/src/da/certificate/mod.rs, nomos-core/src/da/certificate/select.rs, nomos-da/full-replication/src/lib.rs, nomos-services/consensus/src/lib.rs
We really need to select the certificates not the blobs. I refactored everything to fit this. This will help in integrating @Zeegomo work on the certificates mempool.
=> Use selection for blob certificates

nodes/nomos-node/src/bridges/mod.rs, nodes/nomos-node/src/main.rs, nomos-services/mempool/src/backend/mockpool.rs, nomos-services/mempool/src/backend/mod.rs, nomos-services/mempool/src/lib.rs
Add a best effort API to retrieve status of items in the mempool
=> Add mempool status API

nodes/mixnode/Cargo.toml, nodes/nomos-node/Cargo.toml, nomos-cli/Cargo.toml, nomos-http-api/Cargo.toml, nomos-services/consensus/Cargo.toml, nomos-services/data-availability/Cargo.toml, nomos-services/http/Cargo.toml, nomos-services/log/Cargo.toml, nomos-services/mempool/Cargo.toml, nomos-services/metrics/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/storage/Cargo.toml, tests/Cargo.toml
This is needed as Overwatch will be coming with breaking changes.
=> Use specific revision on overwatch

mixnet/topology/src/lib.rs
For a network of nodes in docker environment nodes will need to resolve addresses by themselves.
=> Dns or socket address for mixnet node config

nomos-services/network/src/backends/libp2p/mixnet.rs, nomos-services/network/src/backends/libp2p/mod.rs
Reverts logos-co/nomos-node#445
=> Revert "Reestablish connection when mixclient fails"

nodes/mixnode/Cargo.toml, nodes/nomos-node/Cargo.toml, nomos-cli/Cargo.toml, nomos-http-api/Cargo.toml, nomos-services/consensus/Cargo.toml, nomos-services/consensus/src/lib.rs, nomos-services/data-availability/Cargo.toml, nomos-services/data-availability/src/lib.rs, nomos-services/http/Cargo.toml, nomos-services/log/Cargo.toml, nomos-services/log/src/lib.rs, nomos-services/mempool/Cargo.toml, nomos-services/mempool/src/lib.rs, nomos-services/metrics/Cargo.toml, nomos-services/metrics/src/lib.rs, nomos-services/network/Cargo.toml, nomos-services/network/src/lib.rs, nomos-services/storage/Cargo.toml, nomos-services/storage/src/lib.rs, tests/Cargo.toml
Updated Overwatch rev
Implemented lifecycle for services:
=> Lifecycle update and implementations

nodes/nomos-node/src/bridges/mod.rs, nodes/nomos-node/src/main.rs, nomos-services/storage/src/lib.rs, tests/src/nodes/nomos.rs, tests/src/tests/happy.rs
Add http API to revieve block contents from storage
=> Storage api

ci/Dockerfile, ci/Jenkinsfile.nightly.integration
Add minimal report to the discord notification about the integration tests.
=> CI: Integration tests report

nomos-cli/src/cmds/disseminate/mod.rs, nomos-cli/src/da/disseminate.rs
This is now library code and we should not exit the process if an error is encountered
=> Do not exit the process during dissemination

consensus-engine/README.md, mixnet/node/src/config.rs
Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.
=> fix: typos in the docs

ci/Dockerfile, shell.nix
Update rust for nightly jenkins jobs.
=> Update Jenkins CI to rust 1.73.0

consensus-engine/src/overlay/tree_overlay/tree.rs
Tree implementation returned different results when searching for child committee and then using child committee to find its parent:
```
child_comm_1, child_comm_2 = parent.children;
assert_eq(parent, child_comm_1.parent) // Failed
assert_eq(parent, child_comm_2.parent) // Succeeded
```
Added fix for this case
=> Simulations committee parent lookup issue

Dockerfile, ci/Dockerfile, shell.nix, testnet/Dockerfile
For integration tests and testnet.
=> Bump to rust 1.75

nomos-cli/src/cmds/chat/mod.rs
Limit in flight requests and return requests in the original order
=> Limit in-flight requests in chat app

nomos-cli/src/da/retrieve.rs, tests/src/nodes/nomos.rs, tests/src/tests/cli.rs
A few things for chat app:
* Add a test to verify big blobs are disseminated and returned by a node under normal conditions (no mixnet)
* Warn the user if a requested blob was not returned by a node
=> Add test for big blob dissemination

compose.static.yml, testnet/Dockerfile, testnet/scripts/run_nomos_bot.sh
Initial container for sending ping messages to the testnet every 10 seconds
=> Use chat app as testnet bot

Cargo.toml, consensus/cryptarchia-engine/Cargo.toml, consensus/cryptarchia-engine/src/block.rs, consensus/cryptarchia-engine/src/chain.rs, consensus/cryptarchia-engine/src/config.rs, consensus/cryptarchia-engine/src/crypto.rs, consensus/cryptarchia-engine/src/leader_proof.rs, consensus/cryptarchia-engine/src/ledger.rs, consensus/cryptarchia-engine/src/lib.rs, consensus/cryptarchia-engine/src/time.rs
It's quite a big PR but it's mostly a translation from specs code apart from a few routines that were made more efficient. 
Some stuff is still missing (e.g. orphan proofs) and will be added in future iterations
=> Cryptarchia engine

nodes/nomos-node/src/api.rs, nodes/nomos-node/src/lib.rs, nomos-services/api/src/http/cl.rs, nomos-services/api/src/http/consensus.rs, nomos-services/api/src/http/da.rs, nomos-services/api/src/http/mempool.rs, nomos-services/carnot-consensus/src/lib.rs, nomos-services/mempool/src/backend/mockpool.rs, nomos-services/mempool/src/backend/mod.rs, nomos-services/mempool/src/lib.rs, nomos-services/mempool/src/metrics.rs, nomos-services/mempool/tests/mock.rs
This is a first step towards a more generic block structure that can go with different consensus algorithms
=> Make block id generic in mempool

ledger/cryptarchia-ledger/src/coin.rs, ledger/cryptarchia-ledger/src/config.rs, ledger/cryptarchia-ledger/src/lib.rs, ledger/cryptarchia-ledger/src/nonce.rs, nomos-core/src/crypto.rs, nomos-core/src/header/cryptarchia.rs, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/cryptarchia-consensus/src/leadership.rs, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/cryptarchia-consensus/src/time.rs
This also adds a dummy coin implementation in the ledger. I'm not sure that is the best place, I'd probably prefer something like `wallet` in the future but for now since it's a dummy placeholder I would not spend too much time on this
=> Add cryptarchia leadership module

mixnet/src/lib.rs, mixnet/src/packet.rs, mixnet/src/poisson.rs
=> Remove unnecessary attributes and add doc comments for Mixnet

nomos-services/cryptarchia-consensus/src/lib.rs
I've added an api message to register for updates on newly accepted blocks. This would be used later by mixnet and da api for different things.
=> Cryptarchia block subscribe

nodes/nomos-node/src/lib.rs, nodes/nomos-node/src/main.rs, nomos-da/full-replication/src/lib.rs, nomos-services/api/src/http/consensus/cryptarchia.rs, nomos-services/api/src/http/mempool.rs, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/mempool/Cargo.toml, nomos-services/mempool/src/da/mod.rs, nomos-services/mempool/src/da/service.rs, nomos-services/mempool/src/da/verify/fullreplication.rs, nomos-services/mempool/src/da/verify/mod.rs, nomos-services/mempool/src/lib.rs, nomos-services/mempool/src/verify/mod.rs
Certificate verification in the mempool (follow-up to #634). Tests will be added as the Indexer service nears completion.
=> DA API Certificate verification 

nomos-da/full-replication/src/lib.rs, nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/src/common/mod.rs, nomos-da/kzgrs-backend/src/dispersal.rs, nomos-da/kzgrs-backend/src/lib.rs, nomos-da/kzgrs-backend/src/verifier.rs, nomos-da/kzgrs/Cargo.toml, nomos-da/kzgrs/src/common.rs
This PR implements certificate build and verification methods defined in [nomos-spec/dispersal](https://github.com/logos-co/nomos-specs/blob/master/da/dispersal.py).
VID and Metadata traits are also implemented for future use in the verifier, mempool and indexer services.
=> DA Kzgrs Backend Certificate implementation

nomos-da/kzgrs/Cargo.toml, nomos-da/kzgrs/benches/kzg.rs
Expanded benches cases
Feature gated parallelilzation
=> Da v1 benches expand

Dockerfile, ci/Dockerfile, shell.nix, testnet/Dockerfile, tests/src/nodes/nomos.rs
Update related clippy warnings and ci/testnet related versions.
=> Rust 1.79 stable

nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/src/dispersal.rs, nomos-da/kzgrs-backend/src/encoder.rs, nomos-da/kzgrs-backend/src/global.rs, nomos-da/kzgrs-backend/src/verifier.rs, nomos-da/kzgrs/src/rs.rs, nomos-services/data-availability/verifier/src/backend/kzgrs.rs
Integrate fk20 in encoder
Fixed evaluation domains sizes and usage
=> Da: fk20 encoder

nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/benches/encoder.rs, nomos-da/kzgrs-backend/src/common/mod.rs, nomos-da/kzgrs-backend/src/encoder.rs
* Use rayon in the DA encoder
* Added encoder bench
=> Da: parallel encoder

nodes/nomos-node/Cargo.toml, nodes/nomos-node/src/api.rs, nodes/nomos-node/src/config.rs, nodes/nomos-node/src/lib.rs, nodes/nomos-node/src/main.rs, nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/src/common/blob.rs, nomos-da/kzgrs-backend/src/common/mod.rs, nomos-da/kzgrs-backend/src/dispersal.rs, nomos-services/api/Cargo.toml, nomos-services/api/src/http/consensus/cryptarchia.rs, nomos-services/api/src/http/da.rs, nomos-services/api/src/http/mod.rs, nomos-services/mempool/Cargo.toml, nomos-services/mempool/src/da/verify/kzgrs.rs, nomos-services/mempool/src/da/verify/mod.rs, tests/Cargo.toml, tests/src/nodes/nomos.rs
Expose `add_blob` and `get_range` from DaVerifier and DaIndexer in Nomos Http Api.
=> DA Http Endpoints

nodes/nomos-node/Cargo.toml, nodes/nomos-node/src/main.rs, nomos-libp2p/Cargo.toml, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/data-availability/verifier/src/lib.rs
First step on structure logs in services.
This PR adds:
* A general span with a debug id for the node (just debug mode)
* A base span for consensus
* A base span for da verifier
=> Core services tracing spans

nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/tests/src/indexer_integration.rs
Batch of tests for data availability - full replication to improve coverage
=> chore: Da full replication unit tests update

.github/workflows/build-test.yml, .github/workflows/codecov.yml, nomos-libp2p/Cargo.toml, nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/tests/src/indexer_integration.rs
Check da api for app id and index only when we are supposed to have it stored in the indexer.
=> DA Improve indexer integration test

nodes/nomos-node/src/lib.rs, nomos-da/network/core/Cargo.toml, nomos-da/network/core/src/replication/behaviour.rs, nomos-da/network/core/src/replication/handler.rs, nomos-da/network/core/src/replication/mod.rs
Restructure handler
Wake up polls so they do not hang
Added basic test
=> Da: network replication fix connection

nomos-cli/src/da/network/adapters/mock.rs, nomos-da/kzgrs-backend/src/common/blob.rs, nomos-da/kzgrs-backend/src/common/mod.rs, nomos-da/kzgrs-backend/src/dispersal.rs, nomos-da/kzgrs-backend/src/verifier.rs, nomos-da/network/core/src/protocols/dispersal/mod.rs, nomos-da/network/core/src/protocols/sampling/mod.rs, nomos-services/data-availability/tests/src/verifier_integration.rs
Column index as DABlob field for sampling and other usecases.
=> ColumnIndex in DaBlob

nomos-da/network/core/src/behaviour/validator.rs, nomos-da/network/core/src/protocols/sampling/behaviour.rs, nomos-da/network/core/src/swarm/validator.rs, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/network/src/backends/libp2p/mod.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/network/src/backends/mock/executor.rs, nomos-services/data-availability/network/src/backends/mod.rs, nomos-services/data-availability/network/src/lib.rs
Implement the libp2p backend for the DA network service using the specified swarm and behaviors for a validator.
=> Da: network service backend

nomos-da/network/subnetworks-assignations/src/versions/mod.rs, nomos-da/network/subnetworks-assignations/src/versions/v2.rs
This implements the version of the assignation that mitigates access to blobs without reconstruction.
=> Da: V2, assignations with original replication

.github/workflows/build-docker.yml, Dockerfile, ci/Dockerfile, ci/Jenkinsfile.nightly.integration, testnet/Dockerfile
Updated Docker files and Jenkins configuration with risczero dependency.
Updated Nightly tests to include `disseminate_and_retrieve` tests.
Added gh workflow to build nomos docker image.
=> CI: Nighly tests update and docker build gh workflow

nomos-cli/src/test_utils.rs, nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs, nomos-da/network/core/src/swarm/executor.rs, nomos-da/network/core/src/test_utils.rs, nomos-da/network/subnetworks-assignations/src/lib.rs, nomos-da/network/subnetworks-assignations/src/versions/v1.rs, nomos-da/network/subnetworks-assignations/src/versions/v2.rs, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/network/src/backends/libp2p/common.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/mod.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/sampling/src/lib.rs, nomos-services/data-availability/sampling/src/network/adapters/libp2p.rs, nomos-services/data-availability/sampling/src/network/mod.rs, nomos-services/data-availability/tests/src/common.rs, tests/src/nodes/nomos.rs
In this PR we wrap the networking primitives into a service for later use/integrate in the Executor binary.
This PR implements [part of the executor](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#890a1860b2804e7ebd4c055688c3f9fe). Most important is the initialization of the connections with the [peers in the subnetworks](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#2eca7a41cc59448abf37eea64c3c8242): 
@bacv @danielSanchezQ 
~~There is actually no specific notes on how to chose the peers to be connected with. I'll introduce it from this PR and let everyone review.~~
Added notes to [specification](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#10e8f96fb65c803f …
=> DA: Executor network service

nodes/nomos-executor/Cargo.toml, nodes/nomos-executor/src/api/backend.rs, nodes/nomos-executor/src/api/mod.rs, nodes/nomos-executor/src/config.rs, nodes/nomos-executor/src/lib.rs, nodes/nomos-executor/src/main.rs, nodes/nomos-node/src/api/backend.rs, nodes/nomos-node/src/api/handlers.rs, nodes/nomos-node/src/api/mod.rs, nodes/nomos-node/src/config.rs, nodes/nomos-node/src/lib.rs, nodes/nomos-node/src/main.rs, tests/src/nodes/nomos.rs
This pr implements a separate executor http api, which reuses common endpoint handlers from the nomos node.
=> DA: Executor http api

nomos-da/kzgrs/Cargo.toml, nomos-da/kzgrs/src/kzg.rs
- Add rayon as a dev-dependency
- Modify the original test to add parallelization
=> DA: kzg main testing parallelize proofs checks

compose.static.yml, nodes/nomos-node/src/config.rs, testnet/scripts/run_nomos_node.sh
This change removes graylog from docker compose configuration, as the code will later be updated to use OTLP tracing format.
> [!WARNING]  
=> Testnet: Remove graylog and related containers

Cargo.toml, nomos-core/src/da/mod.rs, nomos-da/kzgrs-backend/benches/encoder.rs, nomos-da/kzgrs-backend/src/lib.rs, nomos-da/network/core/src/lib.rs, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/dispersal/src/adapters/mempool/mod.rs, nomos-services/data-availability/dispersal/src/adapters/mod.rs, nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs, nomos-services/data-availability/dispersal/src/adapters/network/mod.rs, nomos-services/data-availability/dispersal/src/backend/kzgrs.rs, nomos-services/data-availability/dispersal/src/backend/mod.rs, nomos-services/data-availability/dispersal/src/lib.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs
This PR puts together an encoder and the dispersal into a single service **meant for executors**. It receives blobs, encodes them and sends them to the DA network.
This is just the integration of the protocols withing the node. It **uses** [encoding](https://www.notion.so/Encoding-Verification-4d8ca269e96d4fdcb05abc70426c5e7c?pvs=4#9502c48c067e4c6197f919659cc9d4e1) and [dispersal](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#10e8f96fb65c80438a48dfd9f9a451b8):
@megonen @danielSanchezQ @bacv 
Process is complete. Tthis is just the last layer to glue everything together.
No changes
=> DA: Executor dispersal service

nomos-da/kzgrs-backend/src/lib.rs, nomos-da/kzgrs-backend/src/reconstruction.rs
Implements basic reconstruction method for original 50% of columns.
This is somewhat the counterpart of [encoding](https://www.notion.so/Encoding-Verification-4d8ca269e96d4fdcb05abc70426c5e7c). This PR doesn't implement fancy interpolation for missing pieces. It just assumes the original pieces are present and rebuilds it.
@megonen @bacv 
This is a property of the polynomial schema used for encoding.
No
=> DA: Implement data reconstruction from original columns

nomos-da/kzgrs-backend/src/dispersal.rs, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/dispersal/src/adapters/mempool/kzgrs.rs, nomos-services/data-availability/dispersal/src/adapters/mempool/mod.rs, nomos-services/data-availability/dispersal/src/backend/kzgrs.rs, nomos-services/data-availability/dispersal/src/backend/mod.rs, nomos-services/data-availability/dispersal/src/lib.rs
Executor dispersal mempool adapter implementation.
=> Executor: Dispersal service mempool adapter

nodes/nomos-executor/Cargo.toml, nodes/nomos-executor/src/config.rs, nodes/nomos-executor/src/lib.rs, nodes/nomos-executor/src/main.rs, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/dispersal/src/backend/kzgrs.rs, nomos-services/data-availability/dispersal/src/lib.rs
Dispersal service integration and configuration in executor node.
Yes
@bacv @danielSanchezQ 
N/A
N/A
=> Executor: Dispersal service in executor node

.github/workflows/build-test.yml, nomos-da/kzgrs-backend/benches/encoder.rs, nomos-da/kzgrs-backend/benches/verifier.rs
Just an update of benches and check add in CI. As we didn't include a check for them in CI they turned outdated.
Yes
No specification related
---
=> Ci: kzg bench update

nomos-cli/src/da/network/swarm.rs, nomos-da/network/core/Cargo.toml, nomos-da/network/core/src/behaviour/executor.rs, nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs, nomos-da/network/core/src/protocols/dispersal/mod.rs
This PR adds auto reconnection capabilities to the executor dispersal behavior. This is an implementation detail and does not come from any specification per se. But it is heavily related to the [DA dispersal protocol](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#890a1860b2804e7ebd4c055688c3f9fe). 
Behavior is complex but should be self explanatory.
Yes
No
=> DA: Executor dispersal auto stream

nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/cryptarchia-consensus/src/network/adapters/libp2p.rs, nomos-services/cryptarchia-consensus/src/network/mod.rs
This is a refactor to remove an unnecesary spawn task.
:+1: 
@danielSanchezQ @youngjoon-lee 
No specification related
No
=> Consensus: Remove task from consensus network adapter

Dockerfile, ci/Dockerfile, testnet/Dockerfile
Since we're using the `stable` version of Rust, which is 1.82 currently, in [our Github Actions](https://github.com/logos-co/nomos-node/blob/ba726bad84d72c40d258d211fc55085afda6e4a1/.github/workflows/build-test.yml#L30), I updated Rust in Docker images as well.
> [!IMPORTANT]  
> Add a link to the specification document, pointing at the specific section.  
> Any implementation detail that could be considered idiosyncratic and not direct from the specification, should be  
> explained.  
> Always consider what someone new would need to know for the code to make sense, and add this context to it.
No spec related
> [!IMPORTANT]  
> Ping the original specification author(s) and add them as reviewers, alongside any other from the engineering team.  
> You are accountable for the PR and its …
=> Update Rust to 1.82 in Docker images

compose.static.yml, testnet/Dockerfile, testnet/cfgsync/src/config.rs, testnet/scripts/run_nomos_executor.sh, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/api.rs, tests/src/topology/configs/mod.rs, tests/src/topology/mod.rs
Added scripts required to run executor in the docker compose environment. Executor is now available as `nomos-node-3` service and it's http api awailable on port `18083`.
Yes
@bacv
N/A
N/A
=> Testnet: Executor configuration

nomos-mix/network/src/behaviour.rs
As described in the [Tier 1 - Persistent Transmission](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11c8f96fb65c80239ad1e522d83c03cf) spec, we have improved the spec to forward all messages (received from peers) to all other peers immediately, before processing them using Temporal Processor (which delays messages). This change is for low latency and also for low bandwidth. Why? It's highly likely that the node who receives the message is not able to unpack the message because only one node in the mix network can unpack it. If all nodes perform the temporal processing before forwarding messages, the messages will arrive in the desired node too late. Previously we had tried to solve this latency problem by increasing …
=> Mix: Forward all incoming messages immediately without any processing

tests/src/tests/da.rs
Reconstructs original data from half of the blobs in the integration tests using couple of nodes.
Uses the same method added in #808, related [specification](https://www.notion.so/Encoding-Verification-4d8ca269e96d4fdcb05abc70426c5e7c)
@bacv
Yes
No
=> DA: Reconstruct data from incomplete blobs

nomos-mix/core/Cargo.toml, nomos-mix/core/src/persistent_transmission.rs
This PR is based on the PR #844.
This PR implements the actual [Persistent Transmission](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11c8f96fb65c804db7ccfd024f8c44d0) (Tier 1). The protocol details can be found in the link, but I explained the core logic as code comments.
For your background,
Messages that were processed in Tier 2 are gathered in the Persistent Transmission module. They are periodically and sequentially sent to all connected peers. If no message is scheduled, a drop message is sent with a probability.
Yes
@madxor @youngjoon-lee 
Yes
No
> [!WARNING]  
=> Mix: Implement Persistent Transmission (Tier 1)

tests/src/tests/da.rs
Ignore one of DA tests as it fails too frequently.
Related issue: #857, will be solved in subsequent PRs after debugging.
Yes
@bacv 
N/A
N/A
=> CI: Ignore reconstruction test

nomos-cli/src/cmds/executor.rs, nomos-cli/src/cmds/validator.rs, testnet/scripts/run_nomos_executor.sh, testnet/scripts/run_nomos_node.sh, tests/src/tests/da.rs
After testing in testnet some minor issues were found and fixed, the core functionality didn't change.
Yes
@bacv
N/A
N/A
=> Cli: Deserialization and runtime fixes

.github/workflows/codecov.yml
- Coverage workflow output directory renamed to /tmp/codecov
=> fix: Codecov workflow conflicting output directory 

.github/workflows/codecov.yml
- Output directory cleanup - self-hosted runner is reused instance
=> fix: Codecov workflow output directory cleanup

nomos-mix/core/Cargo.toml, nomos-mix/core/src/message_blend/crypto.rs, nomos-mix/core/src/message_blend/mod.rs, nomos-mix/core/src/message_blend/temporal.rs
This PR implements the blend engine as a stream. It is the last PR before integration of streams and replacement of older system. 
It still keeps the old style so it is easy to check they are one and the same.
@youngjoon-lee @danielSanchezQ 
N/A
No
=> Mix: Implement blend as stream + extension

nomos-mix/core/Cargo.toml, nomos-mix/core/src/persistent_transmission.rs, nomos-services/mix/Cargo.toml, nomos-services/mix/src/lib.rs
Refactor that abstracts rng from persistent transmission
Yes
@youngjoon-lee @AlejandroCabeza @danielSanchezQ 
N/A
N/A
=> Mix: Abstract persistent transmission rng

nomos-mix/core/src/message_blend/mod.rs, nomos-mix/core/src/message_blend/temporal.rs, nomos-services/mix/Cargo.toml, nomos-services/mix/src/lib.rs
Refactor abstracts rng from blend
Yes
@youngjoon-lee @AlejandroCabeza @danielSanchezQ 
N/A
N/A
=> Mix: Abstract blend rng

nodes/nomos-node/config.yaml, nodes/nomos-node/src/config.rs, nomos-mix/core/Cargo.toml, nomos-mix/core/src/lib.rs, nomos-mix/core/src/membership.rs, nomos-mix/core/src/message_blend/crypto.rs, nomos-mix/core/src/message_blend/mod.rs, nomos-mix/core/src/persistent_transmission.rs, nomos-mix/message/Cargo.toml, nomos-mix/message/src/error.rs, nomos-mix/message/src/lib.rs, nomos-mix/message/src/mock/mod.rs, nomos-mix/message/src/packet.rs, nomos-mix/network/Cargo.toml, nomos-mix/network/src/behaviour.rs, nomos-mix/network/src/handler.rs, nomos-mix/network/src/lib.rs, nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/tests/src/common.rs, nomos-services/mix/Cargo.toml, nomos-services/mix/src/backends/libp2p.rs, nomos-services/mix/src/backends/mod.rs, nomos-services/mix/src/lib.rs, testnet/cfgsync/Cargo.toml, testnet/cfgsync/src/config.rs, tests/Cargo.toml, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/mix.rs
- Add the trait `MixMessage` and implement `MockMixMessage`.
- Include public keys for the `MockMixMessage`
- Add the struct `Membership`, load it from node/test configurations, and use it for establishing connections and constructing mix messages.
Ja
@youngjoon-lee @AlejandroCabeza @danielSanchezQ 
Ja
Nein
> [!WARNING]  
=> Use public keys for the mock mix message encoding

nomos-mix/core/src/message_blend/mod.rs, nomos-mix/core/src/message_blend/temporal.rs, nomos-mix/core/src/persistent_transmission.rs, nomos-services/data-availability/tests/src/common.rs, nomos-services/mix/src/lib.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs
Decoupled release schedulers so they can be interchanged. Gonna use it later for simulations
Yes
@youngjoon-lee @danielSanchezQ 
N/A
N/A
=> Mix: time abstract from streams

nomos-mix/core/src/message_blend/mod.rs
For nomos-simulations, we need `Sync` for fields in the `MessageBlendStream`. So, instead of using the `futures::BoxStream` that doesn't have `Sync`, I changed it to `Pin<Box<Stream + ... + Sync>>`.
Yes
@danielSanchezQ @youngjoon-lee 
n/a
n/a
> [!WARNING]  
=> Add Sync bound to BoxStream in blend stream

nomos-mix/core/Cargo.toml, nomos-mix/core/src/cover_traffic.rs, nomos-mix/core/src/lib.rs
This gets the implementation of cover traffic as per the [documentation](https://www.notion.so/Nomos-Blend-Network-Tier-3-Cover-Traffic-Module-10b8f96fb65c80cab153de10115e0023?pvs=4#12f8f96fb65c80d094b6f31306c65b70).
This is a temporary measure that will be tested within simulations first.
Yes
@youngjoon-lee @madxor  @danielSanchezQ 
Yes, although it may changes in the future.
No changes intended
=> Mix: Implemented cover traffic

nomos-da/kzgrs/Cargo.toml, nomos-da/kzgrs/benches/rs.rs
Add a benches for rs encode and decode intentded for mixnet
Yes
@danielSanchezQ @youngjoon-lee 
N/A
N/A
=> RS: Add rs encode/decode benches

nomos-mix/core/src/cover_traffic.rs
Add missing derives CoverTrafficSettings
N/A
@danielSanchezQ @AlejandroCabeza 
N/A
N/A
> [!WARNING]  
=> Add derives CoverTrafficSettings

nomos-mix/core/src/cover_traffic.rs
Missing bounds so it works on multithreading environments like simlib
Yes
N/A
N/A
=> Add missing bounds for cover traffic

nomos-mix/core/src/cover_traffic.rs
There was a bug with the lottery that should be fixed now.
Yes
@youngjoon-lee @madxor @danielSanchezQ 
Yes
Yes
=> Mix: Fix bug in cover traffic ticket generation

nomos-mix/message/src/sphinx/mod.rs, nomos-services/data-availability/tests/src/common.rs, nomos-services/mix/Cargo.toml, nomos-services/mix/src/backends/libp2p.rs, nomos-services/mix/src/backends/mod.rs, nomos-services/mix/src/lib.rs, testnet/cfgsync/src/config.rs, tests/src/topology/configs/mix.rs
Now that we have the Sphinx implementation, this PR replaces the mock with the Sphinx implementation.
The mock is still in the code base, so that it can be used for some tests and simulations.
Yes
@youngjoon-lee 
Yes
No
> [!WARNING]  
=> Mix: Use Sphinx instead of mock

nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/benches/reconstruct.rs
This PR adds a benchmark for blob reconstruction simulation. It harness column and blob sizes variants.
yes
N/A
No
> [!WARNING]  
=> Add reconstruct bench

nomos-da/kzgrs/benches/rs.rs
Update the benchmark parameters for rs-decode to the ones used for the [last benchmark results](https://www.notion.so/RS-Decode-Benchmark-14c8f96fb65c802a8238ca263f3d5f89).
N/A
N/A
N/A
> [!WARNING]  
=> Update benchmark parameters for rs-decode.

nomos-core/chain-defs/src/block/mod.rs, nomos-core/chain-defs/src/header/mod.rs, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/cryptarchia-consensus/src/lib.rs
Add basic bandwidth tracing on consensus
Yes
@bacv 
N/A
N/A
> [!WARNING]  
=> feature(tracing): Bandwidth on Consensus

.pre-commit-config.yaml, CONTRIBUTING.md
- Adds `pre-commit` hook configuration.
- Adds a contributor's guide which includes a section about how to install and run `pre-commit`.
Yes
@AlejandroCabeza
N/A
N/A
> [!WARNING]  
=> ci(pre-commit): config and docs

nodes/nomos-executor/Cargo.toml, nodes/nomos-node/Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/blend/Cargo.toml, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/sampling/Cargo.toml, nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/verifier/Cargo.toml, nomos-services/mempool/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/storage/Cargo.toml, nomos-services/system-sig/Cargo.toml, nomos-services/tracing/Cargo.toml, tests/Cargo.toml
Update overwatch dependencies to enable instrument gating.
Closes: https://github.com/logos-co/nomos-node/issues/958
Yes
@bacv 
N/A
N/A
> [!WARNING]  
=> chore(dependencies): Update overwatch dependencies to enable instrument gating.

nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
Replace ad-hoc iterations over the `DaBlob`s on `EncodedData` in Dispersal Service with `into_inter`.
Closes: https://github.com/logos-co/nomos-node/issues/964
Yes
N/A
N/A
> [!WARNING]  
=> chore(encoder): Replace ad-hoc DaBlob iterations

compose.debug.yml, compose.static.yml, nodes/nomos-executor/src/main.rs, nodes/nomos-node/src/main.rs, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/dispersal/src/backend/mod.rs, nomos-services/data-availability/dispersal/src/lib.rs, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/indexer/src/lib.rs, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/network/src/lib.rs, nomos-services/data-availability/sampling/Cargo.toml, nomos-services/data-availability/sampling/src/backend/kzgrs.rs, nomos-services/data-availability/sampling/src/lib.rs, nomos-services/data-availability/verifier/Cargo.toml, nomos-services/data-availability/verifier/src/lib.rs, nomos-tracing/Cargo.toml, nomos-tracing/src/tracing/macros.rs, nomos-tracing/src/tracing/mod.rs, nomos-tracing/src/tracing/otlp.rs, testnet/cfgsync/src/config.rs, testnet/monitoring/grafana/datasources.yaml, testnet/monitoring/tempo.yaml, tests/src/tests/da.rs, tests/src/topology/configs/tracing.rs
Added support for setting arbitrary bytes as a remote trace ID in the nomos-tracing crate.
Enables tracking entity lifecycles (e.g., blobId, txId) across different nodes.
Introduced `info_with_id` and `error_with_id macros` to set a parent ID for the current span.
Yes
@bacv 
N/A
N/A
=> feature(tracing): Trace blob by id in network

compose.debug.yml, compose.static.yml, nomos-services/cryptarchia-consensus/src/lib.rs, testnet/Dockerfile, testnet/cfgsync/src/config.rs, testnet/monitoring/grafana/dashboards.yml, testnet/monitoring/grafana/dashboards/testnet_metrics.json, testnet/monitoring/prometheus.yml, testnet/scripts/run_nomos_executor.sh, testnet/scripts/run_nomos_node.sh, tests/src/tests/da.rs
Configured Prometheus as an OTLP receiver.
Added a sample Grafana dashboard to display pending DA blobs and consensus-processed blocks.
Yes
@bacv 
N/A
N/A
=> feature(tracing): Otlp metrics and preconfigured dashboard

.github/workflows/publish-testnet-image.yml, compose.static.yml
Action for publishing testnet docker image, takes `branch` and `label` variables. At the moment it's setup to be triggered manually from the repository "Actions" section.
Yes
N/A
N/A
N/A
=> chore(ci): Github action to publish testnet docker images

.github/workflows/publish-testnet-image.yml
Remove linux-arm64 until later
=> fix(testnet): Unsupported risc0 platform

Cargo.toml, nomos-services/key-management-system/Cargo.toml, nomos-services/key-management-system/src/backend/mod.rs, nomos-services/key-management-system/src/backends/mod.rs, nomos-services/key-management-system/src/lib.rs, nomos-services/key-management-system/src/secure_key.rs
This PR implements the service layer for the [KMS (key management system)](https://www.notion.so/KMS-key-management-system-16f8f96fb65c8064a529cd0908294088).
This is a partial implementation but it is pretty straight forward to understand from the document. Notice that when implementing the backend we may need to modify things a bit (probably the SecureKey trait).
@youngjoon-lee @danielSanchezQ 
Yes
It does not.
> [!WARNING]  
=> Kms service

.github/workflows/build-test.yml, .github/workflows/codecov.yml
Updates the version of the checkout actions due to being deprecated.
Yes
N/A
N/A
No
> [!WARNING]  
=> fix(ci): Update checkout actions version

Cargo.toml, nodes/nomos-executor/Cargo.toml, nodes/nomos-node/Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/blend/Cargo.toml, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/sampling/Cargo.toml, nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/verifier/Cargo.toml, nomos-services/mempool/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/storage/Cargo.toml, nomos-services/system-sig/Cargo.toml, nomos-services/tracing/Cargo.toml, nomos-services/utils/Cargo.toml, nomos-services/utils/src/lib.rs, nomos-services/utils/src/overwatch/mod.rs, nomos-services/utils/src/overwatch/recovery.rs, nomos-services/utils/src/traits.rs, nomos-utils/Cargo.toml, nomos-utils/src/lib.rs, nomos-utils/src/overwatch_recovery.rs, tests/Cargo.toml
This is a POC for a reusable Recovery system on top of the current Overwatch, without making any modification.
I'd love to get feedback for this as it's more of an initial proposal than anything. 
Also important, I suggest reading the context below.
First step for https://github.com/logos-co/nomos-node/issues/960
*Additional context:*
In order to implement this I had to leverage two existing mechanisms:
- `ServiceState::from_settings` for loading on startup
- `StateOperator::run` for saving every time the state changes
On the one hand, it works.
On the other, it feels way more convoluted than it should. It's usable, but it does require more explaining than it should, which is certainly less than ideal.
I'd argue the best solution would be to offer the Recovery mechanism from within …
=> feature(node-recovery): Implement Overwatch recovery POC

nodes/nomos-executor/Cargo.toml, nodes/nomos-node/Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/blend/Cargo.toml, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/data-availability/dispersal/Cargo.toml, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/sampling/Cargo.toml, nomos-services/data-availability/tests/Cargo.toml, nomos-services/data-availability/verifier/Cargo.toml, nomos-services/mempool/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/storage/Cargo.toml, nomos-services/system-sig/Cargo.toml, nomos-services/tracing/Cargo.toml, tests/Cargo.toml
Integrates the Overwatch's service status sync mechanism.
This PR will be in two steps:
1. Check Overwatch's compatibility by using the [Overwatch's PR](https://github.com/logos-co/Overwatch/pull/41) commit hash.
2. If it's successful, merge the aforementioned PR, update Overwatch's ref and merge this one.
Yes
N/A
N/A
No
> [!WARNING]  
=> chore(service-status): Update deps to integrate Overwatch's service status

nomos-blend/network/src/behaviour.rs, nomos-blend/network/src/handler.rs, nomos-blend/network/src/lib.rs
(The base branch of this PR is the PR https://github.com/logos-co/nomos-node/pull/987.)
This PR is the 3rd step of refactoring connection management: https://www.notion.so/Connection-Management-in-Libp2p-1708f96fb65c8019a6edd2a3b89ff8e2?pvs=4#1768f96fb65c80e58f68ea5300deba40.
This PR drops the `libp2p::Stream` if the peer is detected as malicious or an IO error occurs. 
Since the connection (not the stream) is shared by multiple `Behaviour`s that shares a `Swarm`, the `BlendConnectionHandler` shouldn't close the connection itself. Instead, it drops the inbound and outbound `libp2p::Stream` from the memory. The libp2p doesn't provide an API to explicitly drop `libp2p::Stream`s. Instead, they guide us to just drop them from the memory. Then, the `libp2p::Swarm` decreases the reference count …
=> refactor(blend): drop streams if malicious or on error

nomos-cli/Cargo.toml, nomos-cli/src/cmds/executor.rs, nomos-cli/src/cmds/validator.rs, nomos-cli/src/main.rs
Global tracing_subscriber and stdout logging for cli
=> Set tracing_subscriber for all cli commands

.github/workflows/build-test.yml, Dockerfile, ci/Dockerfile, ledger/nomos-ledger/src/lib.rs, nomos-core/chain-defs/src/proofs/leader_proof.rs, nomos-da/kzgrs-backend/benches/reconstruct.rs, nomos-da/kzgrs-backend/benches/verifier.rs, nomos-da/kzgrs-backend/src/verifier.rs, nomos-da/kzgrs/benches/fk20.rs, nomos-da/kzgrs/benches/kzg.rs, nomos-da/kzgrs/benches/rs.rs, nomos-da/kzgrs/src/kzg.rs, nomos-da/network/core/src/protocols/replication/mod.rs, nomos-services/data-availability/tests/src/common.rs, nomos-services/data-availability/tests/src/indexer_integration.rs, nomos-services/data-availability/tests/src/verifier_integration.rs, nomos-services/mempool/tests/mock.rs, nomos-services/storage/src/backends/mock.rs, nomos-services/storage/src/backends/sled.rs, testnet/Dockerfile
The CI has been updated to run Clippy with the `--all-targets --all-features` flags, to apply lints to the whole codebase. The resulting lints have been also addressed in this PR.
Yes.
N/A
N/A
N/A
> [!WARNING]  
=> chore: run clippy for all targets in workspace

nodes/nomos-node/src/lib.rs, nomos-services/api/src/http/da.rs, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/indexer/src/lib.rs, nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs, nomos-services/data-availability/tests/src/common.rs, nomos-services/data-availability/tests/src/indexer_integration.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/tests/da.rs
Indexer now returns `DaBlob` instead of `Vec<u8>` in the indexer `get_range` api call.
Yes
@bacv
This is a first part of implementing updated DA indexer api defined in https://www.notion.so/NomosDA-Reconstruction-1828f96fb65c80b2bbb9f4c5a0cf26a5#1938f96fb65c80b8ab24f031035f09f5
No
=> chore(da): DA Indexer return DaBlob

nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs, nomos-da/network/core/src/protocols/dispersal/validator/behaviour.rs, nomos-da/network/core/src/protocols/replication/behaviour.rs, nomos-da/network/core/src/protocols/sampling/behaviour.rs, nomos-da/network/core/src/swarm/common/handlers.rs, nomos-da/network/core/src/swarm/common/mod.rs, nomos-da/network/core/src/swarm/executor.rs, nomos-da/network/core/src/swarm/validator.rs, nomos-services/data-availability/sampling/src/lib.rs
Introduced error propagation in validator dispersal and replication behaviors - for now IO errors, should be easy to expand later if needed.
Yes
@bacv 
N/A
N/A
=> chore(da): DA network behaviour errors

.cargo-deny.toml, .github/workflows/build-test.yml
This PR introduces supply chain checks using [cargo-deny](https://github.com/EmbarkStudios/cargo-deny). It does so by adding a cargo-deny config file as described in [their docs](https://embarkstudios.github.io/cargo-deny/checks/cfg.html), and adds a new workflow step to check our dependencies.
In this PR I have not tackled actually fixing any issues that cargo-deny identifies, but I simply **explicitly** ignored them. The config file should act as the central point of truth regarding our dependencies management.
Yes.
N/A
N/A
N/A
> [!WARNING]  
=> chore: add cargo-deny support

tests/Cargo.toml, tests/src/lib.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/tracing.rs
Remove tests module `debug` feature flag so that the `cargo test --all-features` could be used without issues in all modules.
=> chore(tests): Remove tests debug feature flag and replace it with env var

nodes/nomos-node/config.yaml, nomos-da/network/core/src/swarm/common/mod.rs, nomos-da/network/core/src/swarm/common/monitor.rs, nomos-da/network/core/src/swarm/common/policy.rs, nomos-da/network/core/src/swarm/executor.rs, nomos-da/network/core/src/swarm/mod.rs, nomos-da/network/core/src/swarm/validator.rs, nomos-services/data-availability/network/src/backends/libp2p/common.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/tests/src/common.rs, testnet/cfgsync/src/bin/cfgsync-server.rs, testnet/cfgsync/src/config.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/da.rs
This PR introduces the ConnectionPolicy, a policy component designed to guide the decision-making process for both the Connection Monitor and Connection Balancer behaviors.
Yes
@bacv 
N/A - might require it's own specification in the future.
N/A
=> feat(DA): Connection policy and use in monitor

nomos-cli/src/cmds/validator.rs
This PR updates `nomos-cli reconstruct` command to work with DaBlobs instead of blobs of bytes.
Yes.
@romanzac 
Yes.
No.
=> chore: Update nomos-cli reconstruct to work with DaBlob

nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/benches/verifier.rs, nomos-da/kzgrs-backend/src/dispersal.rs, nomos-da/kzgrs-backend/src/verifier.rs, nomos-services/data-availability/tests/src/common.rs, nomos-services/data-availability/tests/src/indexer_integration.rs, nomos-services/data-availability/tests/src/verifier_integration.rs, nomos-services/data-availability/verifier/src/backend/kzgrs.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs
In this PR we clean up the verifier leftovers from the DA protocol spec rewriting. There is no need for signature anymore as we do not attest anything. Also columns indexes are part of the messaging protocol and participation is covered by the network itself.
Related to [spec](https://www.notion.so/NomosDA-Encoding-Protocol-4d8ca269e96d4fdcb05abc70426c5e7c?pvs=4#18a8f96fb65c80c58443db3cc294aeff)
Should be fairly easy to understand.
Yes
No changes
=> chore(DA): Cleanup verifier leftovers

.pre-commit-config.yaml
It was using the wrong syntax. This works now. Thanks @pradovic for the heads up.
Yes.
@ntn-x2 
N/A
N/A
> [!WARNING]  
=> fix: cargo-deny pre-commit hook

Cargo.toml, nomos-blend/network/Cargo.toml, nomos-da/network/core/Cargo.toml, nomos-libp2p/Cargo.toml, nomos-services/blend/Cargo.toml, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/verifier/Cargo.toml
Use the same libp2p version defined in workspace across nomos crates.
Yes
@bacv
N/A
N/A
=> chore: Use libp2p 0.55 as a workspace dependency

.github/workflows/code-check.yml, ledger/nomos-ledger/Cargo.toml, nodes/nomos-executor/Cargo.toml, nodes/nomos-executor/src/config/mod.rs, nodes/nomos-node/Cargo.toml, nomos-blend/network/src/lib.rs, nomos-core/chain-defs/Cargo.toml, nomos-da/full-replication/Cargo.toml, nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs/Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/blend/Cargo.toml, nomos-services/cryptarchia-consensus/Cargo.toml, nomos-services/data-availability/verifier/src/network/adapters/mod.rs, nomos-services/mempool/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/network/src/backends/mock.rs, nomos-services/network/src/backends/mod.rs, nomos-services/storage/Cargo.toml, nomos-services/storage/src/backends/mod.rs, nomos-services/time/Cargo.toml
This PR does two things:
1. Make sure that no implicit feature is exposed that has the same name as an optional dependency (see [Cargo docs](https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies) for more info). This ensures we always have full control over what is exposed to other crates. Unfortunately, I did not find any way to enforce this, so we have to enforce it when PRs are reviewed
2. Introduce [cargo-hack](https://github.com/taiki-e/cargo-hack) to check for all feature combinations for all crates in the workspace. This caught some feature mishandling that has also been addressed in this PR. The check is added as a job to the `code-check` GH workflow. How I started checking for features is because when running `cargo clippy -p nomos-mempool --all-features` …
=> fix: packages and dependencies features

nomos-da/kzgrs-backend/benches/verifier.rs
Just fixes on the verifier bench
N/A
N/A
N/A
=> fix: verifier bench wrong sizes reporting

testnet/cfgsync.yaml
Sample config parameters for cfgsync were incorrect.
=> fix(cfgsync): Dispersal mempool push strategy in cfgsync sample yaml

.cargo-deny.toml
Seems like the crate has a new maintainer.
Yes.
@ntn-x2 
N/A
No.
=> chore: remove humantime from the cargo-deny ignore list

nomos-services/api/src/http/cl.rs, nomos-services/api/src/http/da.rs, nomos-services/api/src/http/libp2p.rs, nomos-services/api/src/http/mempool.rs, nomos-services/api/src/http/storage.rs, nomos-services/api/src/lib.rs, nomos-services/api/tests/todo.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs
Add 10s timeout to http calls. Resolves #1137.
Yes.
@pradovic 
Yes
HTTP requests should return timeout error (internal server error) if they they don't receive response from the response channel in sensible time.
> [!WARNING]  
=> chore(api): add timeout to http calls

.pre-commit-config.yaml
Add `taplo` as a pre-commit hook.
Yes
N/A
N/A
> [!WARNING]  
=> chore(pre-commit): taplo

.github/actions/install-risc0/action.yml, Cargo.toml, Dockerfile, nomos-core/risc0_proofs/Cargo.toml, nomos-core/risc0_proofs/bundle_balance/Cargo.toml, nomos-core/risc0_proofs/covenant_nop/Cargo.toml, nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml, nomos-core/risc0_proofs/ptx/Cargo.toml, testnet/Dockerfile
=> chore: Update risc0 to v2.0.0

.github/actions/install-risc0/action.yml, .github/actions/setup-cargo-cache/action.yml, .github/actions/update-cargo-cache/action.yml, .github/workflows/auto-author.yml, .github/workflows/build-docker.yml, .github/workflows/code-check.yml, .github/workflows/codecov.yml, .github/workflows/packaging.yml, .github/workflows/publish-testnet-image.yml, .github/workflows/rust-latest-version-check.yml, Dockerfile, ci/Dockerfile, rust-toolchain.toml, shell.nix, testnet/Dockerfile
https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-github-action-cve-2025-30066. Tried to use the latest version for everything. If something breaks, I will switch back to the right version. Since Clippy checks skip risc0 building, we do not need to install risc0 in the first place.
Yes.
@ntn-x2 
N/A
No.
=> chore: pin GH actions

.github/actions/install-risc0/action.yml
Use `cargo install` to installed locked `rzup` version.
https://github.com/logos-co/nomos/actions/runs/14100539206/job/39498640686
N/A
N/A
N/A
=> chore: Use cargo install for rzup

.pre-commit-config.yaml, hooks/generate-dependency-graph.sh
Adds a pre-commit hook to generate the dependency graph on commit.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> feature(pre-commit): Dependency graph hook

.github/actions/install-risc0/action.yml, Dockerfile, ci/Dockerfile, testnet/Dockerfile
Use `cargo install` to installed locked `rzup` version in Dockerfiles.
N/A
N/A
N/A
N/A
=> chore: Update dockerfiles to use rzup

nomos-services/blend/src/lib.rs, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/cryptarchia-consensus/src/relays.rs
- Remove leftover comments from https://github.com/logos-co/nomos/pull/1183
- Add time relay to `CryptarchiaConsensusRelays`
Yes
N/A
N/A
> [!WARNING]  
=> chore(cryptarchia-consensus): Add time relay to consensus relays

nomos-services/time/src/backends/ntp/async_client.rs, nomos-services/time/src/backends/ntp/testutils.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/time.rs
=> Socket per ntp request 

.github/workflows/code-check.yml, nomos-services/time/src/backends/ntp/async_client.rs
Fixes https://github.com/logos-co/nomos/issues/1239. Longest steps are anyway the test steps, so adding these additional checks does not have any impact on the "speed" of our CI, at the moment.
Yes.
@ntn-x2 
N/A
No.
> [!WARNING]  
=> chore: run CI steps for all supported OSes

.github/workflows/code-check.yml
Minor issue with propagating OS info to cache keys to avoid cross-job cache poisoning, introduced in https://github.com/logos-co/nomos/pull/1240.
Yes.
@ntn-x2 
N/A
No.
> [!WARNING]  
=> fix: missing OS info in some cache keys

nomos-libp2p/src/config.rs
It should fix a bug in where some nodes in some specific moments (blend broadcasting) would not receive a block just because they sent it.
Its a one-liner
@danielSanchezQ @youngjoon-lee 
N/A
N/A
=> fix(network): Allow receiving self messages

consensus/cryptarchia-engine/src/lib.rs, ledger/nomos-ledger/src/lib.rs, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/cryptarchia-consensus/src/states.rs
- Implement unchecked functions for `Ledger` and `Cryptarchia` so validations can be bypassed for security recovery.
- Split `CryptarchiaConsensus::process_block` into a normal and unchecked version for security recovery.
- Detected and fixed issue where genesis block was being applied two times during security recovery.
- Documentation and naming improvements
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> poc(recovery): Recovery integrity and improvements

.github/workflows/code-check.yml, .taplo.toml, ledger/nomos-ledger/Cargo.toml, nomos-core/risc0_proofs/Cargo.toml, nomos-libp2p/Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/mempool/Cargo.toml, nomos-services/utils/Cargo.toml, nomos-tracing/Cargo.toml, testnet/cfgsync/Cargo.toml, tests/src/nodes/mod.rs
We run pre-commit hooks, but I somehow forgot to add the taplo check in the CI as well, which means of course some TOML files have not been following the taplo formatting. This PR fixes that.
Yes.
@ntn-x2 
N/A
No.
=> chore: enforce taplo formatting in CI

Cargo.toml, nodes/nomos-executor/executor/src/api/backend.rs, nodes/nomos-node/node/Cargo.toml, nodes/nomos-node/node/src/api/backend.rs, nodes/nomos-node/node/src/api/handlers.rs, nomos-core/chain-defs/Cargo.toml, nomos-da/kzgrs-backend/Cargo.toml, nomos-da/kzgrs-backend/src/common/share.rs, nomos-services/api/Cargo.toml, nomos-services/api/src/http/da_shares.rs, nomos-services/api/src/http/storage.rs, nomos-services/data-availability/indexer/Cargo.toml, nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs, nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs, nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs, nomos-services/key-management-system/Cargo.toml, nomos-services/storage/Cargo.toml, nomos-services/storage/src/api/backend/rocksdb/da.rs, nomos-services/storage/src/api/da/mod.rs, nomos-services/storage/src/api/da/requests.rs, nomos-services/storage/src/backends/mock.rs
Use high level functions(like `get_commitments`) in services to interact with underlying database instead of low level `Load/Store` etc functions.
Followup of [New Storage Abstraction](https://github.com/logos-co/nomos/pull/1267). 
Yes
@andrussal 
N/A
N/A
=> Use new storage abstraction layer for storage access

clippy.toml, nomos-blend/core/src/message_blend/crypto.rs, nomos-blend/core/src/persistent_transmission.rs, nomos-blend/message/src/lib.rs, nomos-blend/message/src/mock/mod.rs, nomos-blend/message/src/sphinx/mod.rs, nomos-blend/message/src/sphinx/routing.rs, nomos-blend/network/src/behaviour.rs, nomos-blend/network/src/handler.rs, nomos-services/blend/src/backends/libp2p.rs, nomos-services/blend/src/lib.rs, nomos-services/blend/src/network/libp2p.rs
While browsing through the blend codebase, I found some small bits which could be improved in terms of ease of understanding and better code structure, so I took the chance to apply those changes and open a PR.
Yes.
@ntn-x2 
N/A
No.
=> chore: minor blend refactorings

.github/workflows/code-check.yml
Fixes a arbitrary error happening in https://github.com/logos-co/nomos/pull/1294.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> chore(ci): Update macos image to self-hosted

.github/workflows/code-check.yml
- Fix a cargo issue due to outdated version.
- Remove incorrect comments.
Should Dockerfiles be updated at the same time as well @bacv?
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> chore(ci): Update cargo version

.pre-commit-config.yaml
Add cargo machete to pre-commit hooks.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> chore(pre-commit): Add cargo machete to pre-commit hooks.

.github/workflows/code-check.yml
Nothing, just a check of newly installed rust toolchain
> [!NOTE]  
> Review  
>
the [Specification to Implementation Process document](https://www.notion.so/Specification-to-Implementation-Process-0cd6547233fa43a1a03d6e360de9eb2b).
> [!IMPORTANT]  
> Add a link to the specification document, pointing at the specific section.  
> Any implementation detail that could be considered idiosyncratic and not direct from the specification, should be  
> explained.  
> Always consider what someone new would need to know for the code to make sense, and add this context to it.
> [!IMPORTANT]  
> Ping the original specification author(s) and add them as reviewers, alongside any other from the engineering team.  
> You are accountable for the PR and its rapid resolution, so make sure anyone involved …
=> feature(check): Check cargo version

.github/workflows/code-check.yml
Remove the `rustup override` so `rust-toolchain.toml`'s rust version is not overridden.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> fix(ci): Toolchain version issue

Cargo.toml, nomos-services/api/Cargo.toml, nomos-services/api/src/lib.rs, nomos-services/blend/src/lib.rs, nomos-services/cryptarchia-consensus/src/lib.rs, nomos-services/data-availability/dispersal/src/lib.rs, nomos-services/data-availability/indexer/src/lib.rs, nomos-services/data-availability/network/src/lib.rs, nomos-services/data-availability/sampling/src/lib.rs, nomos-services/data-availability/verifier/src/lib.rs, nomos-services/key-management-system/Cargo.toml, nomos-services/key-management-system/src/lib.rs, nomos-services/membership/src/lib.rs, nomos-services/mempool/src/da/service.rs, nomos-services/mempool/src/tx/service.rs, nomos-services/network/src/lib.rs, nomos-services/sdp/src/lib.rs, nomos-services/storage/src/lib.rs, nomos-services/system-sig/Cargo.toml, nomos-services/system-sig/src/lib.rs, nomos-services/time/Cargo.toml, nomos-services/time/src/lib.rs, nomos-services/tracing/src/lib.rs, nomos-services/utils/src/overwatch/recovery/mod.rs
Make services change their status to `Ready` when they are fully initialised.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> feature(services): Notify ready

nomos-services/sdp/Cargo.toml, nomos-services/sdp/src/backends/ledger.rs, nomos-services/sdp/src/backends/mod.rs
Minor chore to use `thiserror` in sdp service.
=> chore(sdp-service): introduce thiserror

Cargo.toml, nodes/nomos-executor/executor/src/main.rs, nodes/nomos-node/node/src/main.rs, nomos-services/api/tests/todo.rs, nomos-services/mempool/tests/mock.rs, nomos-services/system-sig/src/lib.rs, nomos-services/utils/src/overwatch/recovery/mod.rs, nomos-services/utils/src/overwatch/status/macros.rs
Update Overwatch to include an update in message passing structure. All service lifecycle messages now include a finished signal.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> chore(dependencies): Update overwatch

nomos-services/utils/src/overwatch/status/macros.rs
Fix test flakyness.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> fix(test): Fix wait_until_services_are_ready flakyness.

nomos-da/network/core/src/protocols/sampling/behaviour.rs
Use self instead of destructuring for more concise code.
Is targeting https://github.com/logos-co/nomos/pull/1440
@bacv 
N/A
N/A
=> refactor(da): Use method with self in sampling behaviour

nodes/nomos-executor/config.yaml, nodes/nomos-node/config.yaml, nomos-da/kzgrs-backend/src/common/share.rs, nomos-da/network/core/src/behaviour/executor.rs, nomos-da/network/core/src/behaviour/validator.rs, nomos-da/network/core/src/protocols/sampling/behaviour.rs, nomos-da/network/core/src/protocols/sampling/errors.rs, nomos-da/network/core/src/protocols/sampling/mod.rs, nomos-da/network/core/src/protocols/sampling/streams.rs, nomos-da/network/core/src/swarm/common/handlers.rs, nomos-da/network/core/src/swarm/common/monitor.rs, nomos-da/network/core/src/swarm/executor.rs, nomos-da/network/core/src/swarm/validator.rs, nomos-da/network/messages/src/common.rs, nomos-da/network/messages/src/sampling.rs, nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs, nomos-services/data-availability/network/src/backends/libp2p/common.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/sampling/src/lib.rs, testnet/cfgsync.yaml, testnet/cfgsync/src/config.rs, testnet/cfgsync/src/server.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/da.rs
Sampling protocol specification allows peers to query for shared commitments. Sampling behaviour was expanded to handle such request and response.
Sampling behaviour was also split into several modules for easier navigation.
[Spec](https://www.notion.so/nomos-tech/NomosDA-Sampling-1fd261aa09df81dcb3c6ebc99206a0b1?source=copy_link#22d261aa09df8012b81de31d3d1db354)
Yes
No
=> feat(da): Commitments request and response in sampling protocol

consensus/cryptarchia-sync/Cargo.toml, consensus/cryptarchia-sync/src/config.rs, consensus/cryptarchia-sync/src/lib.rs, consensus/cryptarchia-sync/src/libp2p/behaviour.rs, consensus/cryptarchia-sync/src/libp2p/downloader.rs, consensus/cryptarchia-sync/src/libp2p/errors.rs, consensus/cryptarchia-sync/src/libp2p/provider.rs, nomos-libp2p/src/behaviour/mod.rs, nomos-libp2p/src/config/mod.rs, nomos-libp2p/src/swarm.rs, nomos-services/network/src/backends/libp2p/swarm/mod.rs
This PR addresses some sync networking protocol leftovers what I discovered during IBD and orphan blocks testing
- Add timeouts to requests
- Close streams properly 
Yes. 
@andrussal 
N/A
N/A
=> feat(sync): sync protocol improvements

nodes/nomos-executor/config.yaml, nodes/nomos-node/config.yaml, nodes/nomos-node/node/src/config/blend.rs, nomos-blend/network/src/core/with_core/behaviour/mod.rs, nomos-blend/scheduling/src/membership.rs, nomos-services/blend/src/core/backends/libp2p/settings.rs, nomos-services/blend/src/core/backends/libp2p/swarm.rs, nomos-services/blend/src/edge/backends/libp2p/settings.rs, nomos-services/blend/src/edge/backends/libp2p/swarm.rs, tests/src/topology/configs/blend.rs
Fixes https://github.com/logos-co/nomos/issues/1460. PR based on top of https://github.com/logos-co/nomos/pull/1522.
This PR introduces re-dials for core->core and edge->core connections.
Yes, it's quite a small changeset.
Spec @madxor, code: @ntn-x2, review: @youngjoon-lee.
Yes.
No.
=> feat(blend): dial retries

.github/workflows/code-check.yml, .pre-commit-config.yaml, Cargo.toml, Dockerfile, ci/Dockerfile, nodes/nomos-executor/executor/Cargo.toml, nodes/nomos-executor/executor/src/api/backend.rs, nodes/nomos-node/node/Cargo.toml, nodes/nomos-node/node/src/api/backend.rs, nomos-core/chain-defs/src/mantle/mock.rs, nomos-core/chain-defs/src/mantle/ops/serde_.rs, nomos-da/kzgrs-backend/src/encoder.rs, nomos-da/network/core/src/protocols/replication/mod.rs, nomos-libp2p/src/config/mod.rs, nomos-services/api/Cargo.toml, nomos-services/api/tests/todo.rs, nomos-services/chain-service/Cargo.toml, nomos-services/chain-service/src/network/adapters/libp2p.rs, nomos-services/key-management-system/src/backend/preload.rs, nomos-services/mempool/Cargo.toml, nomos-services/network/Cargo.toml, nomos-services/network/src/backends/libp2p/swarm/mod.rs, nomos-services/time/src/backends/ntp/async_client.rs, rust-toolchain.toml, shell.nix, testnet/Dockerfile, testnet/Dockerfile.debug, testnet/cfgsync/src/bin/cfgsync-client.rs, tests/src/lib.rs, tests/src/topology/configs/time.rs
Update Rust version to 1.89 and address new lint warnings. Fixes https://github.com/logos-co/nomos/issues/1527.
Yes.
@ntn-x2 
N/A
No.
=> chore: update toolchain to 1.89

nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs
Fixes https://github.com/logos-co/nomos/issues/1327.
Yes.
@ntn-x2 
N/A
No.
=> chore: remove unnecessary join handles

zk/groth16-verifier/src/verifier.rs, zk/groth16-verifier/tests/verify_cycles.rs
Fixed imports for different feature combinations
N/A
N/A
N/A
N/A
> [!WARNING]  
=> chore(zk): Minor fixes to groth16 tests

.github/workflows/code-check.yml, nodes/nomos-executor/config.yaml, nodes/nomos-executor/executor/src/main.rs, nodes/nomos-node/config.yaml, nodes/nomos-node/node/src/config/mempool.rs, nodes/nomos-node/node/src/main.rs, nomos-da/network/core/src/swarm/common/handlers.rs, nomos-da/network/core/src/swarm/executor.rs, nomos-da/network/core/src/swarm/mod.rs, nomos-da/network/core/src/swarm/validator.rs, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/network/src/backends/libp2p/common.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/network/src/backends/mock/executor.rs, nomos-services/data-availability/network/src/backends/mod.rs, nomos-services/data-availability/network/src/lib.rs, nomos-services/data-availability/verifier/src/lib.rs, nomos-services/data-availability/verifier/src/network/adapters/common.rs, nomos-services/data-availability/verifier/src/network/adapters/executor.rs, nomos-services/data-availability/verifier/src/network/adapters/validator.rs, nomos-services/data-availability/verifier/src/network/mod.rs, nomos-services/mempool/src/da/service.rs, nomos-services/mempool/src/da/settings.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/topology/configs/da.rs
DA Dispersal specification requires data to be validated before replicating it to subnetwork peers. This change introduces validation response channel to validator dispersal events.
[Spec section](https://www.notion.so/nomos-tech/NomosDA-Subnetwork-Replication-1fd261aa09df811d93f8c6280136bfbb?source=copy_link#1fd261aa09df8141b387d9bfd5c3749f)
Yes
No
=> feat(da): Validate before replicating data

nodes/nomos-node/node/src/config/blend.rs, nomos-services/blend/src/core/backends/libp2p/tests/utils.rs, nomos-services/blend/src/edge/backends/libp2p/mod.rs, nomos-services/blend/src/edge/backends/libp2p/settings.rs, nomos-services/blend/src/edge/backends/libp2p/swarm.rs, nomos-services/blend/src/edge/backends/libp2p/tests/utils.rs, nomos-services/blend/src/test_utils/libp2p.rs
`master` CI is broken since I merged two PRs before first rebasing the second one. I learnt my lesson 😊
=> fix(blend): post-rebase issues

nomos-blend/message/src/encap.rs, nomos-blend/message/src/message.rs, nomos-blend/network/src/core/tests/utils.rs
Fixes https://github.com/logos-co/nomos/issues/1572.
Yes.
Spec: @madxor, impl: @ntn-x2, review: @youngjoon-lee.
Yes. I prompted @madxor to also update the pseudo-code to include the header in the encapsulation and decapsulation logic.
No.
=> chore(blend): merge header into public header

nodes/api-common/src/paths.rs, nodes/nomos-executor/config.yaml, nodes/nomos-executor/executor/src/api/backend.rs, nodes/nomos-executor/http-client/src/lib.rs, nodes/nomos-node/config.yaml, nodes/nomos-node/http-client/src/lib.rs, nodes/nomos-node/node/src/api/backend.rs, nodes/nomos-node/node/src/api/handlers.rs, nomos-core/chain-defs/src/mantle/ops/channel/blob.rs, nomos-services/api/src/http/da.rs, nomos-services/data-availability/network/src/api/http.rs, nomos-services/data-availability/network/src/backends/libp2p/common.rs, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/network/src/lib.rs, nomos-services/data-availability/sampling/src/lib.rs, nomos-services/data-availability/sampling/src/network/adapters/common.rs, nomos-services/data-availability/sampling/src/network/adapters/executor.rs, nomos-services/data-availability/sampling/src/network/adapters/validator.rs, nomos-services/data-availability/sampling/src/network/mod.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs, tests/src/tests/da/api.rs, tests/src/tests/da/disperse.rs
Share commitments message handling in sampling service and integration test that uses one node outside the DA services membership to query data over the sampling protocol. 
[Spec](https://www.notion.so/nomos-tech/NomosDA-Sampling-1fd261aa09df81dcb3c6ebc99206a0b1?source=copy_link#1fd261aa09df819fb622c527d941e44f)
[Related PR](https://github.com/logos-co/nomos/pull/1450)
@bacv 
Yes
No
=> feat(da): Commitments over sampling protocol fixes and integration test

consensus/cryptarchia-engine/src/time.rs, ledger/nomos-ledger/src/cryptarchia/mod.rs
Fix slot endianess in epoch nonce calculations
Yes
@davidrusu author, @zeegomo on the PR
[Yes](https://www.notion.so/nomos-tech/Cryptarchia-v1-Protocol-Specification-21c261aa09df810cb85eff1c76e5798c)
No
> [!WARNING]  
=> fix(ledger): Fix slot endianess in epoch nonce calculations

zk/groth16/Cargo.toml, zk/groth16/src/lib.rs, zk/groth16/src/proof/mod.rs, zk/proofs/poc/src/lib.rs, zk/proofs/pol/src/lib.rs, zk/proofs/poq/src/lib.rs, zk/proofs/zksign/src/lib.rs
Compression of the Groth16 proofs in order to be 128 B
Yes
@thomaslavaur 
Yes
No
> [!WARNING]  
=> fix(zk): Fix proof sizes in proof libraries

nomos-tracing/Cargo.toml
Missing feature was breaking node build
N/A
N/A
N/A
N/A
> [!WARNING]  
=> fix(tracing): Activate serde for url in tracing crate

.github/workflows/code-check.yml, .pre-commit-config.yaml, Cargo.toml, Dockerfile, consensus/cryptarchia-sync/src/lib.rs, consensus/cryptarchia-sync/src/libp2p/behaviour.rs, consensus/cryptarchia-sync/src/libp2p/downloader.rs, consensus/cryptarchia-sync/src/libp2p/messages.rs, consensus/cryptarchia-sync/src/libp2p/mod.rs, consensus/cryptarchia-sync/src/libp2p/provider.rs, consensus/cryptarchia-sync/src/messages.rs, flake.nix, nomos-blend/network/src/core/with_core/behaviour/mod.rs, nomos-da/kzgrs/src/common.rs, nomos-da/kzgrs/src/fk20.rs, nomos-services/key-management-system/src/keys/ed25519.rs, nomos-services/mempool/src/network/messages.rs, nomos-services/mempool/src/network/mod.rs, rust-toolchain.toml, testnet/Dockerfile, tests/src/nodes/mod.rs
Fixes https://github.com/logos-co/nomos/issues/1720.
=> chore: update Rust to 1.90

zk/circuits/utils/Cargo.toml, zk/circuits/utils/src/lib.rs
Works around an issue where calling `temp_env::with_vars` might concurrently modify the same env.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> fix(test): Make test with concurrency issues run sequentially.

Cargo.toml, nodes/nomos-node/node/Cargo.toml, nodes/nomos-node/node/src/lib.rs, nodes/nomos-node/node/src/main.rs, nomos-c/Cargo.toml, nomos-c/build.rs, nomos-c/cbindgen.toml, nomos-c/src/api.rs, nomos-c/src/lib.rs
The intention is to provide an interface to the nomos node for the logos-core project (or any other C based ffi project).
As for now it just provides a way of initializing the node, run it and stopping it. We will decide on the offered API later on and add the functionality.  There are things to solve so this works on logos-core, for example how to distribute the needed binaries, but I guess is a different problem than just exposing the node.
I hope really hope so. Although there is a lot of ffi context needed to fully understand it.
N/A
N/A
N/A
> [!WARNING]  
=> feat(logos-core): Nomos C bindings

testnet/cfgsync.yaml
This PR updates testnet config by adding missing `console"
Yes
@andrussal 
N/A
N/A
=> feat(testnet): add console config

.pre-commit-config.yaml
Remove dependency graph generation from pre-commit hooks since we are not checking it in CI anymore.
N/A
@strinnityk 
N/A
N/A
> [!WARNING]  
=> chore(precommit): Remove dependency graph.

nomos-blend/message/src/crypto/proofs/quota/mod.rs, zk/proofs/poq/src/inputs.rs, zk/proofs/poq/src/lib.rs
fix the input order of PoQ
Yes
@thomaslavaur 
Yes
No
> [!WARNING]  
=> fix(zk): poq input order

Cargo.toml, nodes/nomos-node/node/src/config/mod.rs, nomos-core/chain-defs/Cargo.toml, nomos-core/chain-defs/src/mantle/keys.rs, nomos-services/key-management-system/Cargo.toml, nomos-services/key-management-system/src/encodings/errors.rs, nomos-services/key-management-system/src/encodings/mod.rs, nomos-services/key-management-system/src/keys/mod.rs, nomos-services/key-management-system/src/keys/zk.rs
Implement and integrate Zk key into KMS crate.
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  
=> feat(kms): Integrate ZK key

nodes/api-common/src/paths.rs, nodes/nomos-executor/config.yaml, nodes/nomos-executor/executor/src/api/backend.rs, nodes/nomos-executor/executor/src/lib.rs, nodes/nomos-executor/executor/src/main.rs, nodes/nomos-node/config.yaml, nodes/nomos-node/node/src/api/backend.rs, nodes/nomos-node/node/src/api/handlers.rs, nodes/nomos-node/node/src/config/mempool.rs, nodes/nomos-node/node/src/lib.rs, nomos-services/api/src/http/cl.rs, nomos-services/api/src/http/mantle.rs, nomos-services/api/src/http/mod.rs, nomos-services/chain/chain-leader/src/lib.rs, nomos-services/chain/chain-leader/src/relays.rs, nomos-services/chain/chain-service/src/lib.rs, nomos-services/chain/chain-service/src/relays.rs, nomos-services/data-availability/verifier/src/mempool/kzgrs.rs, nomos-services/mempool/src/backend/mockpool/mod.rs, nomos-services/mempool/src/backend/mod.rs, nomos-services/mempool/src/tx/service.rs, tests/src/nodes/executor.rs, tests/src/nodes/validator.rs
This PR either removes CL reference all together, or renames it to `mantle` where applicable.
Yes
@davidrusu 
NA
NA
=> fix(cl-references): Remove references to CL

testnet/Dockerfile
Build node binary with all features for Leader proof to be built in devmode.
Yes, testnet needs to follow configuration in our CI.
@bacv @strinnityk @AlbertoSoutullo 
N/A
N/A
=> chore(testnet): Build all features to enable pol debug mode

nomos-core/chain-defs/src/sdp/mod.rs, nomos-services/data-availability/network/Cargo.toml, nomos-services/data-availability/network/src/backends/libp2p/executor.rs, nomos-services/data-availability/network/src/backends/libp2p/validator.rs, nomos-services/data-availability/network/src/backends/mock/executor.rs, nomos-services/data-availability/network/src/backends/mod.rs, nomos-services/data-availability/network/src/lib.rs, nomos-services/data-availability/network/src/opinion_aggregator.rs, nomos-services/data-availability/network/src/storage/mod.rs
This PR introduces forming DA samping opinions in da-network, on session change. The next step would be to send these opinions to sdp via adapter, so it the activity proof can be generated.
Yes
@pradovic 
Yes
No
> [!WARNING]  
=> feat(da-network): opinion aggregation
