simulations/src/bin/app/main.rs
simulations/src/network/mod.rs
simulations/src/node/carnot/mod.rs
simulations/src/node/carnot/tally.rs
simulations/src/node/dummy.rs
simulations/src/runner/sync_runner.rs
simulations/src/streaming/io.rs
simulations/src/streaming/naive.rs
simulations/src/streaming/runtime_subscriber.rs
simulations/src/streaming/settings_subscriber.rs

1. Removed different types of network messages that were used to separate adhoc and broadcast messages. That was causing broadcasted but delayed messages be dropped. 
2. Broadcast functionality was added to `Output::BroadcastTimeoutQc` message type.
3. Updated default value of tally to 2.

Simulation network broadcast fix

---

simulations/src/node/carnot/mod.rs

The current view method that is also used to check sim wards used event_builder method. Event builder does not track the current view, it uses carnot engine to get this value.
@al8n should I remove current view variable from the event builder completely?

Get current view directly from the engine

---

simulations/src/bin/app/main.rs
simulations/src/network/mod.rs
simulations/src/node/carnot/messages.rs
simulations/src/node/dummy.rs
simulations/src/runner/async_runner.rs
simulations/src/runner/glauber_runner.rs
simulations/src/runner/layered_runner.rs
simulations/src/runner/mod.rs
simulations/src/runner/sync_runner.rs
simulations/src/settings.rs

First approach to introduce network throughput in simulation app. It works by receiving node throughput from the configuration in kilobytes per second and then uses that value to track node load during each step. 
If the network load of the node is at full capacity the message won't get dropped, but added back to the message cache and retried during the next step.
InmemoryNetworkInterface now requires every payload to have a certain virtual size in bytes. This can be used to easily change the BlockProposal message size according to the number of transactions in it or just making that configurable in settings. Current payload sizes are just size of structs, without assuming size appended by the serialization.

Simulatios network throughput

---

nomos-libp2p/Cargo.toml
nomos-libp2p/src/lib.rs

* [Add initial peer config to nomos-libp2p](https://github.com/logos-co/nomos-node/commit/420ac85155cbd6115eb040511ca83b70bcebef21)
* [Use custom message id to avoid duplicates](https://github.com/logos-co/nomos-node/commit/787060b28ffbda9fe8172bb91855f8c775eae7b8)
* [Expose reference to the inner swarm](https://github.com/logos-co/nomos-node/commit/09edec66bb00b50d54906ca33d03fe490220f64e)

Small additions to libp2p

---

consensus-engine/src/lib.rs
consensus-engine/src/overlay/flat_overlay.rs
consensus-engine/src/overlay/mod.rs
consensus-engine/src/overlay/tree_overlay/overlay.rs
consensus-engine/src/overlay/tree_overlay/tree.rs
simulations/src/node/carnot/mod.rs

Returning an empty committee in case a node have no parent (usual case of root committee members) leads to errors. Being implicit helps here. Also it is as the specs implementation meant it.

Optional parent committee

---

consensus-engine/src/lib.rs

By removing old block we were removing genesis, which is often used.

Fix: genesis pruning in engine

---

consensus-engine/src/overlay/tree_overlay/tree.rs
nomos-services/consensus/src/lib.rs
simulations/src/bin/app/main.rs
simulations/src/network/mod.rs
simulations/src/network/regions.rs
simulations/src/node/carnot/message_cache.rs
simulations/src/node/carnot/mod.rs

According to @bacv, the problem with the current network throughput is if the message size is bigger than the calculated step throughput, then it never gets sent. 
The solution in this PR is "partial send":
e.g.
Let's say, if we have a large message with size 15, and the throughput is 5. In the first step, we mock partially send behavior, so send 5 (remaining message size is 10). In the second step, partially send another 5 (the remaining message size is 5). In the third step, we send the final 5, so the large message can be sent through 3 steps in total.

fix large msg sending logic

---

consensus-engine/src/overlay/tree_overlay/overlay.rs

This cause simulations/test to break if a timeout is triggered

Disable tree rebuild

---

consensus-engine/src/lib.rs
nomos-services/consensus/src/lib.rs
simulations/src/network/mod.rs
simulations/src/node/carnot/event_builder.rs
simulations/src/node/carnot/mod.rs
simulations/src/node/carnot/tally.rs

After introducing the network throughput, simulation fails to advance beyond the first round of consensus. I failed to notice this issue as I was focused on capturing the report for one consensus round.
Do debug this issue I've added a testcase for partial message send correctness.

Test for partial message sending in simulation

---

ci/Jenkinsfile.nightly.integration

Missing cargo flags for nightly integration job. Example result: https://ci.status.im/blue/organizations/jenkins/nomos-node%2Fnightly%2Fnightly-integration/detail/nightly-integration/51/pipeline

Add missing build and test flags

---

simulations/src/bin/app/main.rs
simulations/src/runner/mod.rs
simulations/src/streaming/io.rs
simulations/src/streaming/mod.rs
simulations/src/streaming/naive.rs
simulations/src/streaming/polars.rs
simulations/src/streaming/runtime_subscriber.rs
simulations/src/streaming/settings_subscriber.rs

Two problems occur after the simulation finishes running:
1. The simulation doesn't shut down on its own.
2. If the simulation is stopped or completed, the records that have not yet been persisted are discarded.
It's easier to view the diff by commits.

Simulation graceful shutdown fixes

---

Cargo.toml
mixnet/client/Cargo.toml
mixnet/client/src/config.rs
mixnet/client/src/lib.rs
mixnet/client/src/receiver.rs
mixnet/client/src/sender.rs
mixnet/node/Cargo.toml
mixnet/node/src/client_notifier.rs
mixnet/node/src/config.rs
mixnet/node/src/lib.rs
mixnet/protocol/Cargo.toml
mixnet/protocol/src/lib.rs
mixnet/topology/src/lib.rs
tests/Cargo.toml
tests/src/tests/mixnet.rs

In the previous design #302, the problem was that message senders must specify the mixnet destination (== the IP of `MixnetClient`). Please note that it's different from the message routing destination.
But, in reality, senders doesn't have any information about the IP of `MixnetClient`s available.
Instead, I improved the design like this:
- A `nomos-node` always embed a `MixnetClient` that receives Sphinx packets, reconstructs messages, and sends them to the network backend in its `nomos-node`.
- Actually, this is the same in the previous design.
- If you want to run a `MixnetNode`, you must know at least one `MixnetClient` address.
- In other words, `MixnetNode` operators should run their own `nomos-node` as well.
- When message senders choose 3 `MixnetNode` from `MixnetTopology`, they …

Improved Mixnet design: Random mixnet destination

---

tests/src/lib.rs
tests/src/nodes/nomos.rs

For now, I just increased the randomness of choosing ports, even though this doesn't resolve #311 completely. Later, it woudl be better to leverage the auto port assignment (using the port `0`), but it requires lots of refactorings.

Pick ports more randomly for integration tests

---

tests/src/tests/mixnet.rs

A super tidy PR, replacing hardcoded ports with `get_available_port()` in the mixnet integarion tests. I hope this makes CI happy.

use `get_available_port()` for mixnet integration tests

---

Cargo.toml
nomos-services/http/src/http.rs

New rust version (`1.72`) uses a new dependency resolver. We have conflict depending the version of the crates, so we can overwrite for the whole workspace to the newest one.

Update resolver version in workspace

---

nomos-libp2p/Cargo.toml
nomos-libp2p/src/lib.rs

For a more flexible multiaddrs (i.e. `/dns/localhost/tcp/3000`) to be used with libp2p, tcp needs to be wrapped into dns transport for names to be resolved into ip4 or ip6 addresses.

Wrap tcp into dns transport to resolve hostnames

---

nomos-core/Cargo.toml
nomos-core/src/tx/mock.rs
nomos-services/mempool/Cargo.toml
nomos-services/mempool/src/network/adapters/mock.rs
nomos-services/mempool/tests/mock.rs
nomos-services/network/Cargo.toml
nomos-services/network/src/backends/libp2p.rs

Replaced serde_json with wire for MixnetMessage in libp2p.
NOTE:
To resolve the cyclic package dependency, I changed `nomos-core` to not depend on `nomos-network`.
```
error: cyclic package dependency: package `nomos-core v0.1.0 (/Users/yjlee/repos/nomos-node-mix/nomos-core)` depends on itself. Cycle:
package `nomos-core v0.1.0 (/Users/yjlee/repos/nomos-node-mix/nomos-core)`
... which satisfies path dependency `nomos-core` (locked to 0.1.0) of package `nomos-network v0.1.0 (/Users/yjlee/repos/nomos-node-mix/nomos-services/network)`
... which satisfies path dependency `nomos-network` (locked to 0.1.0) of package `nomos-core v0.1.0 (/Users/yjlee/repos/nomos-node-mix/nomos-core)`
... which satisfies path dependency `nomos-core` (locked to 0.1.0) of package `nomos-consensus v0.1.0 …
```

Use `wire` for MixnetMessage in libp2p

---

ci/Jenkinsfile.prs.linux
ci/Jenkinsfile.prs.macos

Previously builds for all targets had the same lock and certain steps weren't build on macos if linux didn't finish.

Lock builds per commit and target

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs

Added nomos node cli parameter to override the node key in config.yml file.

Set node_key from cli args

---

tests/Cargo.toml
tests/src/tests/mixnet.rs

CI sometimes never stop when running the mixnet integration test, if panic happens from mixnodes due to port conflicts or any others. It's because mixnodes are spawned as async tasks. 
Here, I simply set test timeout, as we do for happy/unhappy integration tests.

Prevent mixnet tests from running forever

---

.github/workflows/pr.yml

Updated and re added github actions for PRs.

Update GH actions for master and prs

---

.github/workflows/master.yml
.github/workflows/pr.yml

`continue-on-error` didn't yield the desired behavior of marking the job failed, but performing other runs - removing it. 
The issue described here: [#365](https://github.com/logos-co/nomos-node/pull/365#discussion_r1312728853)

GH Actions: Fix Windows build

---

mixnet/client/Cargo.toml
mixnet/client/src/config.rs
mixnet/client/src/lib.rs
mixnet/client/src/receiver.rs
mixnet/client/src/sender.rs
mixnet/node/Cargo.toml
mixnet/node/src/config.rs
mixnet/node/src/lib.rs
mixnet/protocol/src/lib.rs
mixnet/topology/src/lib.rs
mixnet/util/Cargo.toml
mixnet/util/src/lib.rs
tests/src/nodes/mixnode.rs
tests/src/nodes/nomos.rs
tests/src/tests/mixnet.rs

This is a very simple solution. Just add a connection cache based on LRU. This solution can only make sure we will not create multiple conn for one `SocketAddr`.

Fix run output fd

---

nodes/nomos-node/src/blob.rs
nodes/nomos-node/src/lib.rs
nomos-core/src/block.rs
nomos-services/consensus/src/committee_membership/mod.rs
nomos-services/consensus/src/leader_selection/mod.rs
nomos-services/consensus/src/lib.rs
simulations/src/bin/app/overlay_node.rs
simulations/src/node/carnot/event_builder.rs
simulations/src/node/carnot/mod.rs

Block refactor

---

mixnet/node/src/lib.rs

So far, the mixnode has spawned a new async task whenever it accepts a new inbound connection from mixclients or other mixnodes. It's good for handling multiple mixclients and other mixnodes concurrently.
But, it's not enough for better performance. Mixnode also needs to spawn a new async task whenever it reads a 'body' from a inbound connection, so that it can handle bodies concurrently which comes from the same source. This is especiallly important if we set delay to Sphinx packets. 
Previously, we hadn’t haven this issue since we had created one-time connections and closed them immediately. But with conn pool added recently, we have this issue. 
This PR makes the `mixnet.rs` test much faster: 20s -> 3s
I'm opening this PR based on the PR #370 because I need #370 to make CI passed. It …

Make mixnode handle bodies coming from the same source concurrently

---

mixnet/node/src/lib.rs
mixnet/util/src/lib.rs

Holding a MutexGuard across an await point is not a good idea (see https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html).
Removing that solves the issues we had with the mixnet test without needing https://github.com/logos-co/nomos-node/pull/370

Fix MutexGuard across await

---

nomos-services/consensus/src/network/adapters/libp2p.rs
nomos-services/network/src/lib.rs

We now wait after the call to 'subscribe' to give the network the time to register peers in the mesh before starting to publish messages
Should fix occurrences of  #329 in testing for the short term

Move wait at network startup

---

Cargo.toml
nomos-services/data-availability/Cargo.toml
nomos-services/data-availability/src/backend/mod.rs
nomos-services/data-availability/src/lib.rs
nomos-services/data-availability/src/network/mod.rs

Notice that traits and/or bounds may be changed. This is an initial approach and things would have to change probably a bit when piping everything together. I'll be implementing the backend and adapters after this.

Initial DA service sketch

---

nomos-services/network/Cargo.toml

This only worked thanks to feature unification with other crates

Add derive feature to serde

---

nomos-services/data-availability/Cargo.toml
nomos-services/data-availability/src/lib.rs
nomos-services/data-availability/src/network/adapters/libp2p.rs
nomos-services/data-availability/src/network/adapters/mod.rs
nomos-services/data-availability/src/network/mod.rs

Implemented libp2p da network adapter

Da service network

---

.github/workflows/master.yml
.github/workflows/pr.yml
simulations/Cargo.toml
simulations/src/bin/app/main.rs
simulations/src/bin/app/overlay_node.rs
simulations/src/node/carnot/timeout.rs
simulations/src/streaming/mod.rs

Windows builds are failing, the exact reason is not obvious. 
After some investigation, the failure is not clear still, but the build fails for polars crate. As this feature is not essential to simulations, I've just made it optional and not built in ci related tests.

Simulations: make polars dependancy optional

---

.github/workflows/codecov.yml

Codecov token should not be required for public repos.

GH Actions: Remove codecov token

---

nodes/nomos-node/config.yaml
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs

Exposed some parameters to be configured via the cli or env variables.
If this approach is acceptable, then I'll create a new PR for metrics configuration, as node currently uses MapMetricsBackend instead of Graphql.

Node envconfig

---

mixnet/node/src/lib.rs
mixnet/topology/src/lib.rs
nodes/nomos-node/config.yaml
tests/src/nodes/mixnode.rs
tests/src/tests/mixnet.rs

The mixnet topology doesn't need to hold `HashMap<MixnetNodeId, Node>`.
`Vec<Node>` is enough.
With `HashMap` with the key type `MixnetNodeId`, it's hard to write config yaml files:
```yaml
topology:
layers:
- nodes:
? - 190
- 75
- 117
- ...
: address: 127.0.0.1:7777
public_key: [190, ...]
```

Simplify mixnet topology

---

nomos-core/src/da/mod.rs

Remove async streams from the DaProtocol trait to avoid creating dependencies on actual I/O. The protocol it's now transformed into a state machine with an input and output buffer.
In addition, a method to create an attestation was added to the trait.

Adopt a sans-IO style for DaProtocol

---

Cargo.toml
nomos-da/full-replication/Cargo.toml
nomos-da/full-replication/src/lib.rs

Add an initial simple but functional implementation for a data availability protocol.
Full replication simply encodes bytes in a single blob which is replicated in all nodes.
For now I've just implemented the DA protocol for this simple one to test it out, we can implement it for more complex constructions in following PRs. At that time, it might be interesting to consider extracting more pieces into independent components

Add full replication implementation for DA

---

nomos-services/data-availability/src/network/adapters/libp2p.rs

Firstly, a failure in deserialization for a network message is not an error especially since we're using a public channel. Secondly, that same channel is shared by different kind of messages so trying to interpret one as the other will surely lead to a unsuccessfull attempt.

Remove failed deserialization error message

---

consensus-engine/src/overlay/branch_overlay.rs
consensus-engine/src/overlay/mod.rs

During research simulation runs tree and branch overlays behave as expected, the only issue was that branch overlay timed out without incrementing the view when it contained single committee. This was not the case for flat and tree overlays.
This change fixes the problem, but to be totally sure, I'd like to ask @0xFugue to rerun all tests with this version and check if branch overlay still correlate to tree overlay results with higher committee count.

Simulation branch with one committee fix

---

nodes/nomos-node/Cargo.toml

We've been using it for a while and we don't plan to switch back to Waku anytime soon.

Change default network backend to libp2p

---

mixnet/README.md
nodes/mixnode/README.md
nodes/mixnode/config.yaml
nodes/nomos-node/README.md
nodes/nomos-node/config.yaml

I wrote documents to explain the mixnet architecture and configurations for mixnodes and mixclients. Please let me know if more clearification is needed.

Add mixnet usage docs

---

nodes/nomos-node/src/bridges/waku.rs
nomos-services/consensus/src/network/adapters/mock.rs
nomos-services/consensus/src/network/adapters/waku.rs
nomos-services/network/src/backends/mock.rs

Fix failing jobs by updating deprecated `timestamp_nanos` method to `timestamp_nanos_opt`.

CI: fix cargo clippy deprecated warnings

---

ci/Dockerfile
ci/Jenkinsfile.nightly.integration

Update the docker image for ci to rust 1.72 and add mixnode build step to integration tests

CI: integrations tests libp2p

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/blob.rs
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-core/src/da/mod.rs
nomos-da/full-replication/src/lib.rs
nomos-services/data-availability/src/backend/memory_cache.rs
nomos-services/data-availability/src/backend/mod.rs
nomos-services/data-availability/src/lib.rs
nomos-services/data-availability/src/network/mod.rs
tests/Cargo.toml
tests/src/nodes/nomos.rs

This PR:
* updates the data availability service to work with generic da protocols
* add the data availability service to the nomos node
Could actually split this but it's not too big and you can find the features grouped by commits anyway

Add da service to nomos node

---

Cargo.toml
nomos-cli/Cargo.toml
nomos-cli/config.yaml
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/cmds/mod.rs
nomos-cli/src/main.rs

Add nomos-cli to hold various utilities for the node.
To start, this commit adds a command to disseminate some
data through the network and build a certificate of correct
dispersal for inclusion in a block.
The idea is to grow this command into an interactive one covering the whole DA and transaction submit process emulating an EZ
Still haven't tested it but not sure we have the corresponding server component in place

[nomos-cli] Add command to disseminate data

---

.github/workflows/codecov.yml
.github/workflows/master.yml
.github/workflows/pr.yml

Added skipped tests in master, pr and codecov. Codecov does not use feature matrix, so only libp2p feature is built and tested, if coverage numbers doesn't suffer too much, I'd leave it as is.

GH: Run integration tests in all actions

---

ci/Jenkinsfile.nightly.integration

Have all binaries in place in case integration tests need them.

Use build all before integration tests

---

nomos-core/src/block/mod.rs

This is the first PR of a coming set in where I'll be polishing the naming/types for blobs. In the block we include a certificate that the block has been dispersed, not a blob itself.

Refactor blob -> Blob certificate in Block

---

tests/src/nodes/nomos.rs

Solves the second bullet of https://github.com/logos-co/nomos-node/pull/415#discussion_r1331206783.
Still the `ten_nodes_happy` won't pass, like below. To resolve this, I'm going to open another PR.
```
waiting... 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0
waiting... 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0
waiting... 1 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0
...
```

test: Spawn the next leader first

---

.github/actions/mingw-env/action.yml
.github/workflows/pr.yml

Compilation on windows for waku features fails with  “corrupt .drectve”. The issue is similar to one described here: https://github.com/rust-lang/rust/issues/112368

GH: Waku windows build configuration

---

nodes/nomos-node/src/bridges/mod.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-services/consensus/src/lib.rs
nomos-services/mempool/src/backend/mockpool.rs
nomos-services/mempool/src/backend/mod.rs
nomos-services/mempool/src/lib.rs
nomos-services/mempool/src/network/adapters/libp2p.rs
nomos-services/mempool/src/network/adapters/mock.rs
nomos-services/mempool/src/network/adapters/waku.rs
nomos-services/mempool/src/network/mod.rs
nomos-services/mempool/tests/mock.rs

Make the mempool generic with respect to the item and remove
mentions of specific transaction formats/traits. This will allow
us to reuse the same code for both coordination layer transactions
and certificates, or in general, whatever items need to be included
in a block.

Make mempool generic

---

nodes/nomos-node/src/bridges/mod.rs
nodes/nomos-node/src/lib.rs
nomos-services/consensus/src/lib.rs
nomos-services/mempool/src/lib.rs
nomos-services/mempool/tests/mock.rs

Overwatch requires all services to have a different service id. Unfortunately, such service id can't depend on generic parameters, which means that we can't have two instances of the mempool service even if they are instantiated with different types. This commit circuments this limitation by adding another type parameter.
I experimented with Overwatch to try relax the service id requirement and instead rely on [TypeId](https://doc.rust-lang.org/std/any/struct.TypeId.html) but unfortunately that is const only on nightly.

Add discriminant type to allow multiple mempool services

---

nodes/nomos-node/src/bridges/libp2p.rs
nodes/nomos-node/src/bridges/mod.rs
nomos-services/mempool/Cargo.toml
nomos-services/mempool/src/lib.rs
nomos-services/mempool/src/network/adapters/libp2p.rs
nomos-services/mempool/src/network/adapters/mock.rs
nomos-services/mempool/src/network/adapters/waku.rs
nomos-services/mempool/src/network/mod.rs

Centralize responsabilities for mempool-network interface in the adapter trait.

Add `send` method to mempool network adapter

---

nodes/nomos-node/src/bridges/mod.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-services/consensus/src/lib.rs

Add a separate mempool for DA certificates. This approach was chosen over a single shared mempool to allow for greater customization.
Also adds the relevant endpoint to add certificates and inspect metrics

Add a second mempool for DA certificates

---

consensus-engine/src/overlay/random_beacon.rs
consensus-engine/tests/fuzz/ref_state.rs
nomos-da/full-replication/Cargo.toml
nomos-services/consensus/src/network/adapters/mock.rs
nomos-services/data-availability/src/lib.rs
nomos-services/metrics/src/lib.rs
nomos-services/network/src/backends/mock.rs
nomos-services/storage/Cargo.toml
nomos-services/storage/src/backends/sled.rs
tests/src/tests/mixnet.rs

As Rust release 1.73, there are new clippy rules which make our CI always fail.

Fix clippy and check warnings on released rust 1.73

---

Cargo.toml
nomos-http-api/Cargo.toml
nomos-http-api/src/lib.rs
nomos-http-api/tests/todo.rs

May be we can change the crate name to `nomos-api`?  Maybe we also support `grpc` endpoint in the future?
The core logic of the PR is not large, but there is a large test case, to test if the swagger docs route works.

Finish the skeleton of the api for nomos-node

---

nomos-libp2p/src/config.rs
nomos-libp2p/src/lib.rs

Reference: https://github.com/logos-co/nomos-node/issues/440#issuecomment-1750011020
- [77de5aa](https://github.com/logos-co/nomos-node/pull/454/commits/77de5aa81a675a53c48af78d05d6780cb37256a8): Added a `gossipsub_config` field into the `nomos_libp2p::SwarmConfig`, so that node operators can configure it. But, it's enough to use the default setting for now.
- [f7b35c6](https://github.com/logos-co/nomos-node/pull/454/commits/f7b35c6a5f950d4567fa66f8f2ae0d6d54710506): refactor: move config-related codes into config.rs

Make libp2p gossipsub config configurable

---

tests/src/tests/unhappy.rs

At the end of the unhappy test, we sometimes check if all nodes have the same timeout_qc. But, this check can be failed if timeout_qcs are from different senders, even though all other fields are the same.
In this check, we want to consider those timeout_qcs as the same timeout_qc.
- 66f80fc25da037cf74d5006665a7975030336b1d: Refactoring
- fcd48aa: Core changes

test(unhappy): mask `sender` when comparing timeout_qcs

---

mixnet/client/Cargo.toml
mixnet/client/src/config.rs
mixnet/topology/src/lib.rs

Closes #459 
@zeegomo 
As @al8n mentioned in https://github.com/logos-co/nomos-node/issues/459#issuecomment-1764760768, the default value of `max_retries` and `retry_delay` have been already defined, so that the default values can be used if nothing is set in the yaml. 
In addition to it, I defined the default of `connection_pool_size` as well.
I'm not sure if this is what you intended. Please let me know if you need something more.

Add default for `MixnetClientConfig::connection_pool_size`

---

nomos-cli/Cargo.toml
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/da/mod.rs
nomos-cli/src/lib.rs
tests/src/tests/cli.rs

This will be useful for other commands that might want to interact with the network to perform tasks related to DA. One example is the upcoming testnet demo.

Extract nomos-cli da stuff into shared module

---

consensus-engine/src/types/committee.rs
nomos-utils/src/lib.rs

Added committee id ser/de, it's needed for simulation topology info.
Also YAML doesn't support deserializing to bytes (https://github.com/dtolnay/serde-yaml/blob/master/tests/test_error.rs#L123), that's why if it's trying to deser a human readable variant, it'll deserialize to string first.

Human serde committeeid

---

nomos-libp2p/src/lib.rs
nomos-services/network/src/backends/libp2p/swarm.rs

We have to use the type of the upstream dependency

Allow deprecated type in Swarm

---

simulations/src/bin/app/main.rs
simulations/src/network/mod.rs
simulations/src/node/dummy.rs
simulations/src/runner/sync_runner.rs
simulations/src/settings.rs

Instead of having to enter big numbers in config file when it's desired to have unlimited bandwidth, use optional value.

Optional network capacity in simulations

---

nomos-core/src/da/attestation/mod.rs
nomos-core/src/da/certificate/mod.rs
nomos-da/full-replication/src/lib.rs
nomos-services/consensus/src/lib.rs

Let's signal to the mempool which items were included in a block already to avoid reinclusion.

Remove block contents from mempool

---

.github/workflows/build-test.yml
.github/workflows/codecov.yml
.gitignore
tests/src/nodes/nomos.rs

Closes #507
If CI fails, integration test artifacts (logs, etc...) are uploaded to Github Actions. 
The uploaded artifacts can be found at the bottom of the `Summary` page of each action.
Currently, we upload artifacts without compressing them (since it's simpler and doesn't cost), but they're automatically compressed as a zip when you download them.

Store logs from failed CI as artifacts

---

nomos-services/consensus/src/lib.rs

Put a hard limit of 1024 blocks in the response returned by GetBlocks to avoid slowing things down. This number was chosen rather arbitrarily. We might want to do some more fine tuning.
Even with the new api, a client could request a very long sequence of blocks (for example because it might be starting up after the chain has been running for a lot of time already) and we don't want that to block a node.
Specifically for the catching up phase, we might want to design a better protocol, but for the moment polling this API multiple times should do it.

Limit GetBlocks response size

---

compose.static.yml
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
testnet/bootstrap_config.yaml
testnet/libp2p_config.yaml
testnet/scripts/run_bootstrap_node.sh
testnet/scripts/run_nomos_node.sh

Configurable da voter and minor improvements to docker compose file.
A copy of this closed PR: https://github.com/logos-co/nomos-node/pull/512

Da voter config for docker compose

---

nomos-services/log/src/lib.rs

This might be helpful in tests or other cases where you want to collect and process logs produced by another application in real time

Add option to provide custom writer to the logger backend

---

nomos-services/log/src/lib.rs

There's currently no way for an app with a logger service to disable log collection.

Add option to not collect logs

---

nomos-cli/src/api/da.rs
nomos-cli/src/api/mempool.rs
nomos-cli/src/api/storage.rs

Use reqwest's `json` method instead of manually serializing body into json so that we don't have to set the content type ourselves (and sometimes forget)

Fix nomos-cli api

---

nomos-da/kzg/Cargo.toml
nomos-da/kzg/src/dynamic_kzg.rs

Previously, we've not set the specific revision of `rust-kzg`. 
CI suddenly began to be failed because there has been a lot of changes on the main branch of `rust-kzg`.
I updated our code according to the latest version of `rust-kzg`.
Also, I set the version of `rust-kzg` in the `Cargo.toml` specifically to prevent `cargo build` from being failed suddenly.

Update code according to the latest `rust-kzg`

---

nomos-core/src/da/certificate/mod.rs
nomos-core/src/da/certificate/select.rs
nomos-core/src/tx/mod.rs
nomos-core/src/tx/select.rs
nomos-core/src/utils/select.rs

After rust 1.75 we can start migrating and use `impl Foo` in return positions in traits. I've been playing around with it a bit. Simple ones are easy to migrate. Once it hits lifetimes, adding `Send`  or using `Stream` makes things a bit more complicated. For now as initial brick we have this.

Unbox select traits

---

consensus-engine/src/lib.rs

Store the tip in a variable and return it when asked.

Set and get blocks tip without filtering

---

consensus-engine/src/overlay/tree_overlay/tree.rs

Added suggested test cases to check sizes of each layer (depth) in tree overlay. The way the test cases are checked could be improved, especially the tree traversal from the bottom to the top.

Tests for tree overlay level sizes

---

nomos-cli/Cargo.toml
nomos-cli/src/api/consensus.rs
nomos-cli/src/cmds/chat/mod.rs
nomos-cli/src/cmds/chat/ui.rs
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/cmds/mod.rs
nomos-cli/src/da/disseminate.rs
nomos-services/log/src/lib.rs

This commit adds a simple demo to showcase the capabilities of the Nomos architecture. In particular, we want to leverage the DA features and explore participants roles.
At the same time, we're not ready to commit to any speficic format or decision regarding common ground yet.
For this reason, we chose to implement the demo at the Execution Zone (EZ) level.
In contrast to the coordination layer, each execution zone can decide on its own format, which allows us to experiment without having to set a standard.
The application of choice for the demo is an (almost) instant messaging app where the messages are broadcast to the public by leveraging the full replication data availability protocol. In this context, the cli app acts as a small EZ disseminating blobs, promoting blob inclusion and …

Add chat demo for testnet

---

compose.static.yml
testnet/bootstrap_config.yaml
testnet/libp2p_config.yaml

To avoid configuring firewall rules for multiple port ranges, nomos http ports are set in the same range for containers and host.
In addition DA storage limit was increased.

Testnet config update for nomos.tech

---

nomos-cli/config.yaml
nomos-cli/src/cmds/chat/mod.rs

This change allows demo app to receive blobs of multiple blocks in parallel, thus making demo app instantaneous (compared to previous version) even on a very fast nomos network.
I encourage you to test it on `testnet.nomos.tech`.
To connect, compile the project and run `./target/debug/nomos-cli chat --network-config nomos-cli/config.yaml --node http://testnet.nomos.tech:18080`
Note: **Be sure to change `nomos-cli/config.yaml` `node_key` to something different in case multiple clients connect to the network**
Note: Try sending unique messages (e.g. don't send "hi"), there are some limitations in DA at the moment.
Note: Long messages gets disseminated, but for some reason won't show up in the chat.

Receive blocks blobs in parallel

---

Cargo.toml
nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/api.rs
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-metrics/Cargo.toml
nomos-metrics/src/lib.rs
nomos-services/api/Cargo.toml
nomos-services/api/src/http/metrics.rs
nomos-services/api/src/http/mod.rs
nomos-services/mempool/Cargo.toml
nomos-services/mempool/src/lib.rs
nomos-services/mempool/src/metrics.rs
nomos-services/mempool/tests/mock.rs

Implementation of nomos metrics service using [prometheus_client](https://github.com/prometheus/client_rust). Before adding more features and metrics the concept validation is needed.
Similar to the tracing crate, nomos metrics service does not own the "main" registry that is used by all other service to put their metrics in. The main registry is created before initializing the node and passed to services to register them selves.
Nomos metrics service is responsible for accessing the registry whenever remote prometheus server queries new metrics (via nomos-api).
Every service that wants to publish metrics need to register them selves during the initialization. After this point individual services are responsible how they collects the metrics. The easiest approach is to track service …

Prometheus metrics service

---

simulations/Cargo.toml

Cargo fails to work because of version conflicts.

bump rayon version to make cargo work

---

nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/da/disseminate.rs
tests/src/tests/cli.rs

To use dissemination app as a bot for chat demo, there needs to be a way to send any binary data to the DA storage.
Nomos chat is encoding ChatMessage with bincode, now dissemination app will be able to send preencoded messages as a bot in the testnet.

Disseminate app file input

---

nomos-cli/src/cmds/chat/mod.rs
nomos-cli/src/cmds/disseminate/mod.rs

Add params to nomos cli app to send chat message and exit the application. This will be used alongside the dissemination app to produce constant traffic in the testnet.
For chat app to decode messages, they need to be in ChatMessage struct, encoded with bincode. Bincode has no external cli tool to encode independantly, so either we need to write that tool, that we would be able to use from scripts, or we use chatapp to do encoding to ChatMessage directly, because it's specific to it.
Dissemination app will still be used for big data blob uploads to the testnet.

Nomos chat app non interactive

---

compose.static.yml
testnet/Dockerfile
testnet/cli_config.yaml
testnet/scripts/run_nomos_bot.sh

Three fixes were requried after the grafana and nomos bot addition:
- Grafana failed to start because of configuration file mode (644), setting it explicitly should help;
- Nomos chat bot cli params were incorrect, and the configuration filename misspelled;
- Nomos chat requires openssl libs, and because "build" image was using different debian version, the "exec" image had dependencies in different place with different versions.

Add testnet cli_config and volume

---

tests/src/lib.rs
tests/src/nodes/nomos.rs
tests/src/tests/cli.rs

This PR will be merged to the PR #580.
When using QUIC (as changed in #580), DA integration tests fail because of the difference between TCP and QUIC.
The tests spawn two nomos-nodes and shutdown the second node in order to run the DA CLI with the same config that the second node used.
When two nodes were spawned, the first node accepted a connection with the libp2p `PeerId` of the second node. And, the connection is not automatically disconnected when the second node is shutdown because it's not TCP.
So, if the DA CLI is started with the same `PeerId` and tries to connect to the first node, the first node rejects the connection because it already has the previous connection for the `PeedId`.
Of course, we can make the DA CLI use a different `PeerId`. But instead, I modified the tests to …

Fix integration tests for QUIC environment

---

nomos-libp2p/Cargo.toml
nomos-libp2p/src/lib.rs
nomos-services/network/src/backends/libp2p/swarm.rs
tests/src/lib.rs
tests/src/nodes/nomos.rs
tests/src/tests/cli.rs

This PR will be merged to the PR #569, not `master`.
I replaced TCP with QUIC in the `nomos-libp2p` crate, which will be used by the `mixnet` network backend.
Plus, I bumped libp2p to the latest version that contains the libp2p `stream` protocol, which is necessary for mixnet communication.
DA integration tests will be failed because of the difference between TCP and QUIC when connections are closed. I'll open another PR to modify tests for QUIC environment.

Use QUIC for libp2p

---

nomos-services/storage/Cargo.toml
nomos-services/storage/src/backends/mod.rs
nomos-services/storage/src/backends/rocksdb.rs
nomos-services/storage/src/bin/rocks.rs

Implement RocksDB storage service, not use `TransactionDB` as it does not support open in read-only mode.

RocksDB Storage service

---

compose.yml
testnet/README.md

I found that nodes in the testnet settings listen on [`0.0.0.0:18080`](https://github.com/logos-co/nomos-node/blob/bab83fe2b814d7c45043871e3c2cdf95758204f0/testnet/bootstrap_config.yaml#L68) for HTTP API, but the `compose.yml` is exporting [8080](https://github.com/logos-co/nomos-node/blob/e51865fe3303b54cc2b66cb1fb090a0989c4c91f/compose.yml#L9) instead of 18080. I think we need to change `compose.yml` to expose 18080 because all other configs (`compose.static.yml` and `prometheus-config.yml`) are using 18080. Please correct me if I'm wrong.

Expose 18080 for HTTP API in Testnet

---

.github/workflows/build-test.yml
nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/api.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-cli/Cargo.toml
nomos-cli/src/cmds/chat/mod.rs
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/da/disseminate.rs
nomos-services/api/Cargo.toml
nomos-services/api/src/http/cl.rs
nomos-services/api/src/http/consensus.rs
nomos-services/api/src/http/da.rs
nomos-services/carnot-consensus/Cargo.toml
nomos-services/carnot-consensus/src/network/adapters/mod.rs
nomos-services/carnot-consensus/src/network/adapters/p2p.rs
nomos-services/data-availability/Cargo.toml
nomos-services/data-availability/src/network/adapters/mod.rs
nomos-services/data-availability/src/network/adapters/p2p.rs
nomos-services/mempool/Cargo.toml
nomos-services/mempool/src/network/adapters/mod.rs
nomos-services/mempool/src/network/adapters/p2p.rs
nomos-services/network/Cargo.toml
nomos-services/network/src/backends/libp2p/swarm.rs
nomos-services/network/src/backends/mixnet/mod.rs
nomos-services/network/src/backends/mod.rs
tests/Cargo.toml

Added the `mixnet` compilation feature to enable the mixnet network backend instead of the libp2p network backend.
Because the external API of the mixnet network backend is exactly the same as the libp2p network backend, we can reuse the existing network adapter of consensus, mempool, and DA without any modification. The one thing I changed is selecting a proper network backend using conditional compilation.
I didn't modify the integration test for mixnet yet. I'll do it in the PR #597.

Added `mixnet` compilation feature

---

mixnet/src/client.rs

As we previously [discussed](https://github.com/logos-co/nomos-node/pull/588#discussion_r1504470412), I implemented `Stream` for `MixClient`, so that we don't need to spawn a `MixClientRunner` task internally.
The existing unit tests and integraiton tests ensure that this change works well.

Implement Stream for MixClient

---

.github/workflows/build-test.yml

Rocksdb fails because something is not supported in the gnu toolchain

CI: Use windows msvc 

---

nomos-services/network/src/backends/libp2p/swarm.rs

This is a very simple PR.
Because we're already printing a log with a proper log level according to the error type in the [upper layer](https://github.com/logos-co/nomos-node/blob/fae4c994d70a32453fb16f38245329ecc31ad519/nomos-services/network/src/backends/libp2p/mixnet.rs#L158-L158), we can remove the duplicate log in the `swarm.rs`. That log is actually very annoying because one of these error types always happen when a node A is trying to dial to itself for creating a p2p stream (to send mix packets). That type of log doesn't need to be printed with the ERROR level because it's ignored in the upper layer.
p.s. We may be able to improve the logic to not try to dial if the peer address is mine, but I couldn't find any sophisticated way to check if the address is mine.

Remove duplicate error log in network service

---

nomos-da/kzgrs-backend/src/encoder.rs
nomos-da/kzgrs-backend/src/verifier.rs
nomos-da/kzgrs/Cargo.toml
nomos-da/kzgrs/benches/kzg.rs
nomos-da/kzgrs/src/kzg.rs

Reuse precomputed evaluations instead of evaluating the polynomial for each proof

Reuse evaluations when computing proofs

---

nomos-da/kzgrs/Cargo.toml
nomos-da/kzgrs/benches/kzg.rs

Added parallelization simulation to benches (next step is to add it to implementation which should be trivial).
Discovered and fixed and issue with the evaluation domain. This need to be fixed in the final `kzgrs-backend` which has the same issue.

Da v1 multiple proofs bench

---

nomos-services/mempool/src/tx/metrics.rs

After https://github.com/logos-co/nomos-node/pull/626 metrics feature was missing one generics parameter.

Added missing generic param to the mempool metrics

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs

To build a node without tracing use `cargo build -p nomos-node --no-default-features`.
Node already has the ability to disable logging with `None` option for the LoggingBackend.

Feature flag to toggle tracing

---

nomos-da/kzgrs-backend/benches/encoder.rs
nomos-da/kzgrs-backend/src/encoder.rs
nomos-da/kzgrs/benches/fk20.rs
nomos-da/kzgrs/src/fk20.rs

Toeplitz part 1 can be cached as it just depends on the global parameters. From benches it improves performance in around a *40%* for the proofs computations.

Da: cache toeplitz1

---

compose.static.yml

Otherwise we get:
```
ERROR: for libp2p-node-1  pull access denied for nomos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: for libp2p-node-2  pull access denied for nomos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: for libp2p-node-3  pull access denied for nomos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: for chatbot  pull access denied for nomos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for nomos, repository does not exist or may require 'docker login': denied: requested access to the …
```

fix missing build settings for libp2p nodes

---

shell.nix

Apparently it works with the .dev version of the package, we avoid bringing up the binaries I think.

Just use openssl.dev, no binaries for nix-shell

---

Dockerfile
ci/Dockerfile
nomos-core/src/header/cryptarchia.rs
shell.nix
testnet/Dockerfile

Added a `allow[dead_code]` for `Nonce` in consensus for Clippy.
Unused methods in da libp2p will be handled in a separate PRs.

CI: Rust 1.80

---

Cargo.toml
nomos-cli/Cargo.toml
nomos-cli/src/api/mempool.rs
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/cmds/mod.rs
nomos-cli/src/da/disseminate.rs
nomos-cli/src/da/mod.rs
nomos-cli/src/da/network/adapters/mock.rs
nomos-cli/src/da/network/adapters/mod.rs
nomos-cli/src/da/network/mod.rs
nomos-cli/src/da/retrieve.rs
nomos-cli/src/lib.rs
nomos-core/src/da/mod.rs
nomos-da/kzgrs-backend/src/common/blob.rs
nomos-da/kzgrs-backend/src/common/mod.rs
nomos-da/kzgrs-backend/src/dispersal.rs
nomos-services/data-availability/network/Cargo.toml
nomos-services/data-availability/network/src/backends/mock/executor.rs
nomos-services/data-availability/network/src/backends/mock/mod.rs
nomos-services/data-availability/network/src/backends/mod.rs
nomos-services/data-availability/network/src/lib.rs

Dispersal command with simplified da network backend mock for executor.
This version has simplified configuration for the cli, with a plan to improve it in subsequent pull requests with more options for different da network backends (libp2p or mock).
Full replication option was removed as an option in the dispersal cli app.

DA: Dispersal in Cli App with mock backend

---

nodes/nomos-node/src/api.rs
nomos-core/src/da/blob/mod.rs
nomos-core/src/da/mod.rs
nomos-da/kzgrs-backend/src/common/blob.rs
nomos-da/storage/src/fs/mod.rs
nomos-da/storage/src/rocksdb/mod.rs
nomos-services/api/src/http/da.rs
nomos-services/data-availability/indexer/src/lib.rs
nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/indexer/src/storage/mod.rs
nomos-services/data-availability/tests/src/indexer_integration.rs
nomos-services/data-availability/verifier/src/lib.rs
nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/verifier/src/storage/mod.rs
nomos-services/storage/src/backends/mock.rs
nomos-services/storage/src/backends/mod.rs
nomos-services/storage/src/backends/rocksdb.rs
nomos-services/storage/src/backends/sled.rs
nomos-services/storage/src/lib.rs

To allow verification of multiple columns for the same encoded data in a single node Blob holds column_idx, which is later used in da storage service and indexer.

DA: Store and load multiple columns for the same blob in a single node

---

nomos-da/network/subnetworks-assignations/Cargo.toml
nomos-da/network/subnetworks-assignations/src/lib.rs
nomos-da/network/subnetworks-assignations/src/versions/mod.rs
nomos-da/network/subnetworks-assignations/src/versions/v1.rs

Implemented subnetwork handler as per the [initial specification](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c?pvs=4#ae967b1d50fe4a278e4750bf6a812772), **skipping PoV** for now:
```python
from itertools import cycle
from typing import List, Sequence, Set, TypeAlias
import ipaddress
PoV: TypeAlias = bytes
type NodeDef = tuple[PoV, ipaddress.ip_address]
def calculate_subnets(
nodes_list: Sequence[NodeDef], num_subnets: int, dispersal_factor: int
) -> List[Set[NodeDef]]:
"""
Calculate in which subnet(s) to place each node.
Fills up each subnet up to a count in an iterative mode
"""
nodes_list = sorted(nodes_list)
nodes = cycle(nodes_list)
subnets = [
set(next(nodes) for _ in range(dispersal_factor)) for _ in range(num_subnets)
]
return subnets
```

DA: Implement subnetwork handler v1

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-cli/src/da/network/backend.rs
nomos-da/network/subnetworks-assignations/src/versions/v1.rs
nomos-libp2p/src/config.rs
nomos-libp2p/src/lib.rs
nomos-services/data-availability/network/Cargo.toml
nomos-services/data-availability/network/src/backends/libp2p/validator.rs
tests/Cargo.toml
tests/src/nodes/nomos.rs

Use da network service with verifier backend in Nomos Node.

DA Network in node

---

nomos-services/data-availability/sampling/src/backend/kzgrs.rs
nomos-services/data-availability/sampling/src/backend/mod.rs
nomos-services/data-availability/sampling/src/lib.rs

Added a few structural fixes
Added pruning from service

DA: Sampling service backend fixes

---

nodes/nomos-node/src/api.rs
nomos-cli/src/api/mempool.rs
nomos-cli/src/cmds/disseminate/mod.rs
nomos-cli/src/da/disseminate.rs
nomos-cli/src/da/network/backend.rs
nomos-services/api/src/http/mempool.rs
tests/Cargo.toml
tests/src/lib.rs
tests/src/tests/cli.rs

Integration tests for nomos cli dispersing Kzgrs encoded data. For faster test times, the number of columns is set to `32`, cache is disabled.
To run these tests locally:
```bash
cargo test -p tests  -- --nocapture
```

DA: Nomos Cli dispersal tests

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-services/data-availability/indexer/src/lib.rs
nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/tests/Cargo.toml
nomos-services/data-availability/tests/src/verifier_integration.rs
nomos-services/data-availability/verifier/Cargo.toml
nomos-services/data-availability/verifier/src/backend/kzgrs.rs
nomos-services/data-availability/verifier/src/lib.rs
nomos-services/data-availability/verifier/src/storage/adapters/rocksdb.rs
tests/Cargo.toml
tests/src/nodes/nomos.rs

Verifier and Indexer services were created and tested in a simplified node, this PR integrates them into the Nomos Node.

DA: Verifier and Indexer in Node

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/api.rs
nodes/nomos-node/src/config.rs
nodes/nomos-node/src/lib.rs
nodes/nomos-node/src/main.rs
nomos-core/src/block/builder.rs
nomos-da/network/subnetworks-assignations/src/versions/v2.rs
nomos-services/api/Cargo.toml
nomos-services/api/src/http/consensus/cryptarchia.rs
nomos-services/api/src/http/da.rs
nomos-services/cryptarchia-consensus/Cargo.toml
nomos-services/cryptarchia-consensus/src/lib.rs
nomos-services/data-availability/indexer/Cargo.toml
nomos-services/data-availability/indexer/src/lib.rs
nomos-services/data-availability/sampling/src/backend/kzgrs.rs
nomos-services/data-availability/sampling/src/backend/mod.rs
nomos-services/data-availability/sampling/src/lib.rs
nomos-services/data-availability/sampling/src/network/adapters/libp2p.rs
nomos-services/data-availability/tests/Cargo.toml
nomos-services/data-availability/tests/src/common.rs
nomos-services/data-availability/tests/src/indexer_integration.rs
tests/Cargo.toml
tests/src/nodes/nomos.rs

Add sampling to consensus.
Added a verification of block so it is not included if as a non-proposer you do not see the included blobs in your sample view.
As a proposer include only the blobs that you see available in your sample view.

DA: Consensus sampling

---

nodes/nomos-node/Cargo.toml
nodes/nomos-node/src/api.rs
nodes/nomos-node/src/lib.rs
nomos-da/network/core/src/protocols/sampling/behaviour.rs
nomos-da/network/core/src/protocols/sampling/mod.rs
nomos-services/api/src/http/consensus/cryptarchia.rs
nomos-services/api/src/http/da.rs
nomos-services/api/src/http/mempool.rs
nomos-services/cryptarchia-consensus/src/lib.rs
nomos-services/data-availability/indexer/src/lib.rs
nomos-services/data-availability/network/src/backends/libp2p/validator.rs
nomos-services/data-availability/sampling/Cargo.toml
nomos-services/data-availability/sampling/src/lib.rs
nomos-services/data-availability/sampling/src/storage/adapters/mod.rs
nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/sampling/src/storage/mod.rs
nomos-services/data-availability/tests/src/common.rs
nomos-services/data-availability/tests/src/verifier_integration.rs
nomos-services/data-availability/verifier/src/network/adapters/libp2p.rs
nomos-services/mempool/src/da/service.rs
tests/src/nodes/nomos.rs

Incoming sample request handling in Sampling service.

DA: Incoming sampling request handling

---

nomos-da/network/core/src/protocols/sampling/behaviour.rs
nomos-da/network/messages/proto/sampling.proto
nomos-da/storage/src/fs/mod.rs
nomos-services/data-availability/indexer/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/network/src/backends/libp2p/validator.rs
nomos-services/data-availability/sampling/src/lib.rs
nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs
nomos-services/data-availability/sampling/src/storage/mod.rs

Sampling a node that might have multiple columns for the same blob, sampling request needs to contain the column index. This field is also defined in the specification, a more thorough spec and code comparison will be needed.

DA: Column index in the sample requests

---

nomos-services/data-availability/sampling/src/storage/adapters/rocksdb.rs

This PR adds a get_blob implementation on the rocksdb Adapter for the sampling service.

Implemented get_blob on sampling rocksdb adapter

---

nomos-services/cryptarchia-consensus/src/lib.rs

I found this when running the fuzz test in #629. If the parent of the block being processed is missing, we may encounter `LedgerError::ParentNotFound` as well as `cryptarchia_engine::Error::ParentMissing`. Although the real error handling logic is not implemented yet, I think both errors need to be checked for future implementations.

Add missing error check: `LedgerError::ParentNotFound`

---

nomos-da/kzgrs-backend/benches/verifier.rs

Updated `kzgrs-backend/benches/verifier.rs` according to the updated `DaBlob` and `DaVerifier.verify` definitions.

DA: Fix compliation errors in KZG backend bench

---

.github/workflows/codecov.yml

Few changes to tweak coverage workflow to occupy less disk space and run tests.

chore: Improve coverage workflow

---

.github/workflows/codecov.yml

A dummy PR to check the rule in https://github.com/logos-co/nomos-node/pull/653 is applied.

Make coverage workflow name clearer.

---

nomos-da/network/core/src/behaviour/executor.rs
nomos-da/network/core/src/behaviour/mod.rs
nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
nomos-da/network/core/src/swarm/common.rs
nomos-da/network/core/src/swarm/executor.rs
nomos-da/network/core/src/swarm/mod.rs
nomos-da/network/core/src/swarm/validator.rs

Added executor composited behaviour and executor swarm.

DA: Executor behaviour + swarm

---

Dockerfile
ci/Dockerfile
ci/Jenkinsfile.nightly.integration
testnet/Dockerfile

This PR updates the Docker images used in the Jenkins nightly integration tests. The changes include:
- Switching the Rust base image from Debian 11 (bullseye) to Debian 12 (bookworm).
- Adding `risczero` and related dependencies to the CI Docker image.
- Installing `cargo` dependencies as the Jenkins user in the CI environment.
- Updating all Dockerfiles to use Debian 12-based Rust images and ensuring `gcc` and `g++` are installed along with other dependencies.
These changes do not need to comply with the specification as they are strictly CI-related.
Yes, the PR updates CI-related Dockerfiles and Jenkins configurations to use the latest dependencies and ensures that the build environment is correctly configured to run nightly integration tests. No functional changes to the product …

CI: Jenkins risczero setup

---

.github/actions/prune-vm/action.yml
.github/workflows/build-test.yml
.github/workflows/codecov.yml

- Remove Android, Dotnet and Haskell support from Ubuntu Github runner to free up disk space. About 15 GB freed. 
- Add local `actions/prune-vm`
- Update coverage and PR workflows

fix: Coverage and PR workflows - no space left on device

---

nomos-da/network/core/src/protocols/replication/behaviour.rs

This PR tests functionality implemented in https://github.com/logos-co/nomos-node/pull/680 and subsequent code changes, which should follow [replication spec](https://www.notion.so/NomosDA-Network-Specification-c6664294d630470ba20aefb21a218f8c)
Closes https://github.com/logos-co/nomos-node/issues/773
Comments are added to the `test_replication_behaviour()` to explain what is expected.
@bacv @danielSanchezQ 
Yes
Tests were successful, no changes are required to the specification

DA: Replication behavior membership test

---

nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
nomos-da/network/core/src/protocols/dispersal/validator/behaviour.rs
nomos-da/network/core/src/protocols/sampling/behaviour.rs

Since Rust 1.82.0, the following error occurs from `cargo clippy`. This PR fixes this by removing the `else` clause, as suggested by clippy.
https://github.com/logos-co/nomos-node/actions/runs/11405557657/job/31737297344
```
Error:    --> nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs:543:9
|
543 |         let Either::Left(event) = event else {
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this pattern will always match, so the `else` clause is useless
= help: consider removing the `else` clause
= note: `-D irrefutable-let-patterns` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(irrefutable_let_patterns)]`
```
> [!IMPORTANT]  
> Add a link to the specification document, pointing at the specific section.  
> Any implementation detail that …

chore: clippy: remove irrefutable `let...else` patterns in DA

---

nodes/nomos-node/Cargo.toml
nomos-da/network/core/Cargo.toml
nomos-da/network/messages/Cargo.toml
nomos-mix/network/Cargo.toml
nomos-services/api/Cargo.toml
nomos-services/data-availability/dispersal/Cargo.toml
nomos-services/system-sig/Cargo.toml
testnet/cfgsync/Cargo.toml

Changes all tokio deps to use the latest stable one at `1.x`.
...
N/A
N/A

Chore: Use tokio 1 in deps

---

.gitignore
nomos-mix/core/src/cover_traffic.rs

Add clone and copy to CoverTrafficSettings
N/A
@danielSanchezQ @AlejandroCabeza 
N/A
N/A
> [!WARNING]  

Add clone and copy to CoverTrafficSettings

---

nomos-services/mix/src/backends/libp2p.rs

Due to a subtle timing difference, incoming messages from other peers can arrive before the module that handles them is initialized. We pass those incoming messages to the module through the channel, and if that module is not initialized yet, the channel returns SendError. The application should not panic at this point, because the module will initialize shortly and handle subsequent incoming messages just fine.
Yes
@youngjoon-lee 
Yes
No
> [!WARNING]  

Mix: Don't panic on SendError in libp2p mix backend

---

nodes/nomos-node/config.yaml
nomos-mix/core/src/cover_traffic.rs
nomos-mix/core/src/membership.rs
nomos-services/data-availability/tests/src/common.rs
nomos-services/mix/src/lib.rs
tests/src/nodes/executor.rs
tests/src/nodes/validator.rs

This PR integrates the cover traffic module (implemented in #910) to the `MixService`.
Regarding `CoverTrafficSettings`, I've seen that some parameters in the `CoverTrafficSettings` can be derived from parameters in other settings (e.g. num_hops). So, I defined the `CoverTrafficExtSettings` that contains only parameters that the user must specify. All other parameters are derived from other settings.
Yes
@youngjoon-lee @danielSanchezQ 
Yes
No
> [!WARNING]  

Mix: Integrate cover traffic to mix service

---

nomos-mix/message/src/mock/mod.rs
nomos-services/storage/src/backends/rocksdb.rs

The following error occurs since clippy has been updated to the latest. This PR removes empty lines under the comment documents.
```
error: empty line after doc comment
Error:   --> nomos-mix/message/src/mock/mod.rs:8:1
|
8  | / /// A mock implementation of the Sphinx encoding.
9  | |
| |_
10 |   const NODE_ID_SIZE: usize = 32;
|   ------------------------- the comment documents this constant
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_doc_comments
= note: `-D clippy::empty-line-after-doc-comments` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::empty_line_after_doc_comments)]`
= help: if the empty line is unintentional remove **it**
```
Yes
N/A
N/A
N/A
> [!WARNING]  
> Do not merge the …

clippy: remove empty lines under comment documents

---

nodes/nomos-node/src/config.rs
nomos-mix/core/Cargo.toml
nomos-mix/core/src/conn_maintenance.rs
nomos-mix/core/src/lib.rs
nomos-mix/core/src/membership.rs
nomos-mix/network/Cargo.toml
nomos-mix/network/src/behaviour.rs
nomos-mix/network/src/handler.rs
nomos-mix/network/src/lib.rs
nomos-services/data-availability/tests/src/common.rs
nomos-services/mix/src/backends/libp2p.rs
nomos-services/mix/src/backends/mod.rs
tests/src/topology/configs/mix.rs

For spam protection and resiliency, the Tier 1 design contains the [Connection Maintenance](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11c8f96fb65c806db454e80add388ab7), which measures [frequencies](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11f8f96fb65c8093a228d6448e41fa7e) of several incoming messages, and close/open connections to maintain the reasonable quality of delivery. 
How frequencies are measured is defined in the [Frequencies Measurement](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11c8f96fb65c80f5b047eade5dae58cd). How to close/open connections is …

Mix: Add connection maintenance

---

nodes/nomos-node/Cargo.toml
nomos-core/chain-defs/src/wire.rs
nomos-da/network/core/Cargo.toml
nomos-da/network/core/src/protocols/dispersal/executor/behaviour.rs
nomos-da/network/core/src/protocols/mod.rs
nomos-da/network/core/src/protocols/sampling/behaviour.rs
nomos-services/mempool/Cargo.toml

Replace remaining bincode calls throughout the code with wire calls.
Closes: https://github.com/logos-co/nomos-node/issues/728
Yes
N/A
N/A
> [!WARNING]  

refactor: Replace remaining bincode calls with wire.

---

nomos-blend/message/src/mock/error.rs
nomos-blend/message/src/mock/mod.rs

Closes #956
As explained in #956, this PR fixes `MockBlendMessage` to correctly check if the current layer is the last. Previously, it has been used `[0u8; 32]` to represent a dummy node ID, but it is common that users use the `[0u8; 32]` as an actual node ID. Then, the check logic fails. So, this PR uses `[u8::MAX; 32]` as a dummy node ID, and return error if users use it as an actual node ID. I think this fix is good enough because it's just a mock (used in simulations).
Yes
@youngjoon-lee 
Yes
No
> [!WARNING]  

fix(blend): correctly check the last layer in `MockBlendMessage`

---

nomos-da/kzgrs-backend/src/encoder.rs

Implement Iterator over DaBlob for EncodedData
Closes: https://github.com/logos-co/nomos-node/issues/943
Yes
N/A
N/A
> [!WARNING]  

feature(encoder): Implement Iterator over DaBlob for EncodedData

---

nomos-da/kzgrs-backend/src/common/mod.rs
nomos-da/kzgrs-backend/src/encoder.rs
nomos-da/kzgrs-backend/src/verifier.rs

Use only commitment hash on encoder and verifier.
Closes: https://github.com/logos-co/nomos-node/issues/972
Yes
Yes
No, it actually updates code according to [spec](https://www.notion.so/NomosDA-Cryptographic-Protocol-4bf3bb62cfb64422ab48b5b60aab6a73#0ce1b4fca39341f4b6c6cecafcfe3fab).
> [!WARNING]  

feature(kzgrs): Use only commitment hash on encoder and verifier.

---

Dockerfile
ci/Dockerfile
testnet/Dockerfile

This PR addresses a problem with dependency resolution for rust:1.82.0-slim-bookworm and latest cargo-binstall v1.10.20. 
```
cargo install cargo-binstall --version 1.10.20
Updating crates.io index
Installing cargo-binstall v1.10.20
Updating crates.io index
error: failed to compile `cargo-binstall v1.10.20`, intermediate artifacts can be found at `/tmp/cargo-installIR4Yju`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
failed to select a version for the requirement `log = "^0.4.24"`
candidate versions found which didn't match: 0.4.22, 0.4.21, 0.4.20, ...
location searched: crates.io index
required by package `cargo-binstall v1.10.20`
if you are looking for the prerelease package it needs to be specified …
```

fix: Temporarily downgrade cargo-binstall to 1.10.19

---

nomos-blend/core/src/conn_maintenance.rs

Before we start implementing the abstracted connection management in earnest, I fixed a bug in the Blend connection maintenance.
As defined in the [Tier 1](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#921a42427ddd4dfbb489f168022249fa) spec, the list of peers detected as malicious must be continuously maintained to ensure they are excluded from subsequent connection establishments (as implemented in [here](https://github.com/logos-co/nomos-node/blob/blend-maintain-malicious-peers/nomos-blend/core/src/conn_maintenance.rs#L136-L136)). Since the current implementation does not retain this list, this PR resolves the issue.
FYI, the current spec doesn't define a logic to reset malicious peers.
A refactoring with the …

fix(blend): maintain malicious peers continously

---

nomos-services/key-management-system/Cargo.toml
nomos-services/key-management-system/src/backend/mod.rs
nomos-services/key-management-system/src/backend/preload.rs
nomos-services/key-management-system/src/keys/ed25519.rs
nomos-services/key-management-system/src/keys/mod.rs
nomos-services/key-management-system/src/lib.rs
nomos-services/key-management-system/src/secure_key.rs

This PR implements a naive KMS backend, which preloads all keys from the setting struct provided by an user. As we've been currently doing, the user must specify all keys in the config file, for example.
This backend provides key operations on only the keys preloaded. It doesn't support generating new keys. 
This is the most simplest version of the KMS backend. We'll be able to design an ideal backend once the requirement from the validator protocol is determined clearly. A possible approach may be making the backend hold a single master key and derive all keys from the master key along with a key ID provided by user, deterministically. This approach is almost the same as the HD key derivation, which most of cyrpto wallets are using, or any other deterministic key derivation algorithms. …

feat(kms): add the preload backend

---

nomos-blend/core/Cargo.toml
nomos-blend/core/src/conn_maintenance.rs
nomos-blend/network/Cargo.toml
nomos-blend/network/src/behaviour.rs
nomos-blend/network/src/handler.rs
nomos-blend/network/src/lib.rs
nomos-services/blend/Cargo.toml
nomos-services/blend/src/backends/libp2p.rs
nomos-services/data-availability/tests/src/common.rs
tests/src/topology/configs/blend.rs

(The base branch of this PR is the PR #986.)
This PR is the 2nd step in the journey of connection management refactoring: https://www.notion.so/Connection-Management-in-Libp2p-1708f96fb65c8019a6edd2a3b89ff8e2?pvs=4#1768f96fb65c80e58f68ea5300deba40.
In the previous implementation, the logic for connection monitoring was handled at the `Behaviour` level. Specifically, the `Behaviour` periodically evaluated the status of ALL peers, disconnected malicious peers, and selected new peers to connect with. However, I've found that this approach is cumbersome. Managing the bulk result from ALL peers was more complex than I expected. Furthermore, peers actually don't need to be monitored within a shared time window; it’s sufficient to monitor each peer individually at its own interval since each …

refactor(blend): perform conn monitoring in the ConnectionHandler level

---

Dockerfile
ci/Dockerfile
nomos-blend/core/src/membership.rs
nomos-blend/network/Cargo.toml
nomos-blend/network/src/behaviour.rs
nomos-blend/network/src/handler.rs
nomos-blend/network/src/lib.rs
nomos-libp2p/Cargo.toml
nomos-libp2p/src/lib.rs
nomos-services/blend/Cargo.toml
nomos-services/blend/src/backends/libp2p.rs
nomos-services/data-availability/tests/Cargo.toml
nomos-services/network/src/backends/libp2p/swarm.rs
testnet/Dockerfile

This PR is the last one of refactoring connection management.
https://www.notion.so/Connection-Management-in-Libp2p-1708f96fb65c8019a6edd2a3b89ff8e2?pvs=4#1768f96fb65c80e58f68ea5300deba40
This PR adds the following actions:
- Dial new peers if needed.
- Deny a stream of a newly established connection in certain conditions.
The detailed logic is:
- `Behaviour` maintains three sets of peers (healthy, unhealthy, and malicious) based on the output of connection monitoring added in the PR #987.
- `Behaviour` determines whether new connections need to be established, based on the number of peers in those three sets. If so, the `Behaviour` emits an event to the `Backend`, so that the `Backend` can select random peers and request `Swarm` to dial them.
- `Behaviour` denies the stream of …

refactor(blend): establish new connections, or deny new streams

---

.github/workflows/packaging.yml

Release page for Nomos Node. Produces a release page from a hardcoded template and attaches the bundled binaries.
There's still room for improvement although that's left for a future iteration. If you want to double check what's remaining of this task, please check [this issue](https://github.com/logos-co/nomos-node/issues/997).
A draft release page has been produced by this workflow. You can check it in the [releases](https://github.com/logos-co/nomos-node/releases) page or go to the specific [release](https://github.com/logos-co/nomos-node/releases/tag/untagged-744160d81ec986d5de2e).
Closes: #1002 
Yes
N/A
N/A
No
> [!WARNING]  

feature(ci): Nomos Node release page

---

nomos-blend/core/src/persistent_transmission.rs
nomos-services/blend/src/lib.rs

So far, the `PersistentTransmissionStream` has been accepting and returning `Vec<u8>`. It's fine in general because the blend protocol deals with only byte arrays, doesn't need to interpret its contents. 
Nevertheless, it's better to make it handle generic type, not only `Vec<u8>`, especially for the [nomos-simulation](https://github.com/logos-co/nomos-simulations). I was updating the simulation to deal with a certain `struct`, instead of just `Vec<u8>`, in order to make the simulation more powerful. Of course, it's okay to serialize the `struct` into `Vec<u8>` and deserialize it back. But, it's more efficient to pass the `struct` to the `PersistentTransmissionStream`, as it is.
This change doesn't bring downsides to our implementation. Even, it simplifies the code.
Yes
@youngjoon-lee …

refactor: make `PersistentTransmission` accept generic type, not only `Vec<u8>`

---

Dockerfile
ci/Dockerfile
testnet/Dockerfile

Unpin `cargo binstall` version, the change was made in an attempt to pin risc0 version, but has no effect and the `risc0` issue in Docker images was solved in this [PR](https://github.com/logos-co/nomos-node/pull/1041)

Unpin cargo binstall version

---

nomos-services/tracing/src/lib.rs
nomos-tracing/src/lib.rs
nomos-tracing/src/panic.rs
testnet/monitoring/tempo.yaml

Panic were not intercepted and sent to tracing subscriber before, this PR provides ability to do that.
A minor change to the Tempo config for the testnet was made - by default Tempo now listens on the localhost only, `0.0.0.0` is required to be set in the config explicitly.
Yes
@bacv
N/A
N/A

feature(tracing): Nomos tracing ability to set panic hook

---

.github/workflows/codecov.yml

Fixes https://github.com/logos-co/nomos-node/issues/1019. Self-hosted runners (both macos and linux) have now support for `rustup` binary. Infra repo issue: https://github.com/status-im/infra-ci/issues/174#issuecomment-2659690561. Running workflows: [linux](https://github.com/logos-co/nomos-node/actions/runs/13365314080/job/37321774933) and [macos](https://github.com/logos-co/nomos-node/actions/runs/13365348318/job/37321874239).
Yes.
@ntn-x2 
N/A
N/A
> [!WARNING]  
* [z] 1. Description added.
* [z] 3. Main contact(s) (developers and specification authors) added
* [z] 5. Link PR to a specific milestone.

chore: revert codecov workflow to using self-hosted runners

---

nomos-services/cryptarchia-consensus/src/lib.rs
nomos-services/cryptarchia-consensus/src/relays.rs

Group relays into one single entity to avoid passing around so many arguments at once. This is also immediately useful as newer features require to add new relay parameters to functions, with which Rust's limit is surpassed (making linters fail).
Also, reorder `CryptarchiaConsensus` generics so they match the declaration order, and improve the naming of one generic for clarity.
Yes
N/A
No
> [!WARNING]  

chore(consensus): Group relays

---

nomos-services/blend/Cargo.toml
nomos-services/blend/src/lib.rs
nomos-services/cryptarchia-consensus/Cargo.toml
nomos-services/cryptarchia-consensus/src/lib.rs
nomos-services/data-availability/indexer/Cargo.toml
nomos-services/data-availability/indexer/src/lib.rs
nomos-services/data-availability/network/Cargo.toml
nomos-services/data-availability/network/src/lib.rs
nomos-services/data-availability/sampling/Cargo.toml
nomos-services/data-availability/sampling/src/lib.rs
nomos-services/data-availability/verifier/Cargo.toml
nomos-services/data-availability/verifier/src/lib.rs
nomos-services/key-management-system/Cargo.toml
nomos-services/key-management-system/src/lib.rs
nomos-services/mempool/Cargo.toml
nomos-services/mempool/src/da/service.rs
nomos-services/mempool/src/tx/service.rs
nomos-services/network/Cargo.toml
nomos-services/network/src/lib.rs
nomos-services/storage/Cargo.toml
nomos-services/storage/src/lib.rs
nomos-services/system-sig/Cargo.toml
nomos-services/system-sig/src/lib.rs
nomos-utils/Cargo.toml
nomos-utils/src/lib.rs
nomos-utils/src/lifecycle.rs

Currently all OverWatch services share the common code to listen shutdown signal. This PR refactors this code into `nomos-utils`
Yes
@andrussal 
N/A
N/A
> [!WARNING]  

refactor: extract `should_stop_service` into nomos-utils

---

.github/actions/install-risc0/action.yml
.github/actions/setup-cargo-cache/action.yml
.github/workflows/code-check.yml
.github/workflows/codecov.yml
nomos-services/utils/src/overwatch/recovery/operators.rs

Use the pull request ref (`head_ref`) or, if absent, the branch name (`ref`) to trigger the Docker build workflow. It also re-adds the `github_token` input for the risczero action as without it the CI is throttled.
Since it seems GitHub is not strictly enforcing rules on stored caches either, I also opted for splitting the test caches into one for each OS, so that they are both faster to run.

fix: docker triggering job

---

nodes/nomos-node/config.yaml
nomos-da/network/core/src/behaviour/executor.rs
nomos-da/network/core/src/behaviour/validator.rs
nomos-da/network/core/src/maintenance/balancer.rs
nomos-da/network/core/src/maintenance/mod.rs
nomos-da/network/core/src/protocols/replication/behaviour.rs
nomos-da/network/core/src/swarm/common/balancer.rs
nomos-da/network/core/src/swarm/common/mod.rs
nomos-da/network/core/src/swarm/common/monitor.rs
nomos-da/network/core/src/swarm/common/policy.rs
nomos-da/network/core/src/swarm/executor.rs
nomos-da/network/core/src/swarm/mod.rs
nomos-da/network/core/src/swarm/validator.rs
nomos-da/network/core/src/test_utils.rs
nomos-da/network/subnetworks-assignations/src/lib.rs
nomos-da/network/subnetworks-assignations/src/versions/v1.rs
nomos-da/network/subnetworks-assignations/src/versions/v2.rs
nomos-services/data-availability/network/src/backends/libp2p/common.rs
nomos-services/data-availability/network/src/backends/libp2p/executor.rs
nomos-services/data-availability/network/src/backends/libp2p/validator.rs
nomos-services/data-availability/tests/src/common.rs
testnet/cfgsync/src/bin/cfgsync-server.rs
testnet/cfgsync/src/config.rs
tests/src/nodes/executor.rs
tests/src/nodes/validator.rs
tests/src/topology/configs/da.rs

DAConnectionBalancer and ConnectionBalancerBehaviour, responsible for maintaining the required number of connections per subnetwork.
- `ConnectionBalancerBehaviour` - A network behaviour that interacts with the swarm, tracking connection events and dialing new peers based on the balancer’s output.
- `DAConnectionBalancer` - Implements ConnectionBalancer, periodically evaluating connected peers and identifying subnetworks with missing peers.
- Polled at regular intervals, assessing the number of peers connected per subnetwork.
- Uses MembershipHandler to determine eligible peers and applies SubnetworkConnectionPolicy to decide how many peers should be connected.
- Only concerned with missing peer connections for now, it does not close excess connections per subnetwork yet, but should be …

feat(DA): Connection balancer behavior

---

.github/actions/setup-cargo-cache/action.yml
.github/rust_update_issue_template.md
.github/workflows/rust-latest-version-check.yml
.github/workflows/rust-stable-check.yml
rust-toolchain.toml

* Pin the toolchain version to a specific version to avoid any overnight breaking changes in dependencies (since we also don't commit the `Cargo.lock` file)
* Introduce a cronjob action that checks for a new release compared to the one in the toolchain file, and create a new ticket only the first time it is detected. Example of a [successful run,](https://github.com/logos-co/nomos-node/actions/runs/13566503368), a [successful run for an existing ticket](https://github.com/logos-co/nomos-node/actions/runs/13566526760), and the [created ticket](https://github.com/logos-co/nomos-node/issues/1087).
Yes.
@ntn-x2 
N/A
N/A
> [!WARNING]  

chore: pin Rust toolchain version

---

Cargo.toml
ledger/nomos-ledger/Cargo.toml
nomos-core/chain-defs/Cargo.toml
nomos-core/risc0_proofs/Cargo.toml
nomos-core/risc0_proofs/bundle_balance/Cargo.toml
nomos-core/risc0_proofs/covenant_nop/Cargo.toml
nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml
nomos-core/risc0_proofs/ptx/Cargo.toml
nomos-services/cryptarchia-consensus/Cargo.toml

Nomos ci, docker files and github actions pin the risc0 server to a specific verions. In the process of updating the risc0, our build dependencies needs to be updated as well. 
Caught in `nomos-e2e-tests` run, lost the original error message but it was about incompatible risc0 client and host server.
Since `nomos-core/risc0_proofs` is excluded from the workspace, the versions in that crate will need to be updated manually.
N/A
@bacv @zeegomo 
N/A
N/A

fix(risc0): Align risc0-build and risc0-zkvm with the host server version

---

testnet/cfgsync/Cargo.toml
testnet/cfgsync/src/bin/cfgsync-client.rs
testnet/cfgsync/src/bin/cfgsync-server.rs
testnet/cfgsync/src/client.rs
testnet/cfgsync/src/config.rs
testnet/cfgsync/src/lib.rs
testnet/cfgsync/src/repo.rs
testnet/cfgsync/src/server.rs
tests/src/topology/configs/da.rs

It was observed that after cfgsync (used in testnet to create and distribute node configs to hosts that register) updates the da peer addressbook to host ip, the peer ids were shuffled and didn't correspond to actual peer id that is assigned to host.
The issue was in `fn update_da_peer_addresses`, hashmap was iterated and the iteration index was used to pick host, believing it will correspond to the peerid assignation order.
- Added tests and fix for this issue.
- For more ergonomic tests, cfgsync server and client modules were extracted from cfgsync binaries.
Yes
@bacv 
N/A
N/A

fix: Cfgsync tests for DA addressbook update

---

nomos-da/network/core/Cargo.toml
nomos-da/network/core/src/maintenance/balancer.rs
nomos-da/network/core/src/maintenance/monitor.rs
nomos-da/network/core/src/protocols/dispersal/mod.rs
nomos-da/network/core/src/protocols/replication/mod.rs
nomos-da/network/core/src/protocols/sampling/mod.rs
nomos-da/network/core/src/test_utils.rs

Update `libp2p_swarm_tests` usage to tokio version. 
Nomos-da sampling tests don't use in memory transport. 
Fix membership in tests.
Yes, it is trivial.
N/A.
N/A.
N/A.
> [!WARNING]  

chore: switch tests to use tokio ephemerals + nomos-da sampling tests to in memory

---

nomos-da/network/core/src/protocols/sampling/behaviour.rs
nomos-da/network/messages/src/sampling.rs
nomos-services/data-availability/dispersal/Cargo.toml
nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs
nomos-services/data-availability/dispersal/src/adapters/network/mod.rs
nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
nomos-services/data-availability/network/src/backends/libp2p/common.rs
nomos-services/data-availability/sampling/src/lib.rs
testnet/cfgsync.yaml
testnet/cfgsync/Cargo.toml
testnet/cfgsync/src/config.rs
testnet/cfgsync/src/lib.rs
testnet/cfgsync/src/server.rs
tests/src/nodes/executor.rs
tests/src/tests/da/disperse.rs
tests/src/topology/configs/da.rs

Dispersal would halt after sending blob with more than 2 chunks in it, the problem was in dispersal service expecting number of confirmations from subnetwork nodes that corresponded to the number or rows, not the number of columns.
Yes, related issue https://github.com/logos-co/nomos-node/issues/1046, might not close yet.
@bacv @danielSanchezQ 
Yes
No

fix(DA): Dispersal service expects correct number of verifier responses

---

nomos-services/api/src/http/mempool.rs
nomos-services/data-availability/dispersal/src/adapters/mempool/kzgrs.rs
nomos-services/data-availability/dispersal/src/adapters/mempool/mod.rs
nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
nomos-services/mempool/src/da/service.rs
nomos-services/mempool/src/lib.rs
tests/src/common/da.rs
tests/src/tests/da/disperse.rs

When the same data and metadata are dispersed repeatedly - dispersal succeeds, but response from the executor mempool is `Err(ExistingItem)`. Before, this error was considered as failure by Dispersal service, now it is considered as success.
Yes
@bacv, @danielSanchezQ 
Yes
No

fix(DA): Disperse succeeds when data and metadata is the same

---

nomos-blend/core/src/conn_maintenance.rs
nomos-blend/network/src/lib.rs

Closes https://github.com/logos-co/nomos/issues/944.
Instead of having a single parameter `effective_message_tolerance`, now we have two separate parameters: `effective_message_malicious_tolerance` and `effective_message_unhealthy_tolerance`. Each tolerance is intended for use in detecting malicious connections and unhealthy connections, respectively, as defined in the [spec](https://www.notion.so/Nomos-Blend-Network-Tier-1-Persistent-Transmission-Module-10b8f96fb65c807cb1e8f92a7f41a771?pvs=4#11c8f96fb65c806db454e80add388ab7). Please see the issue for more details.
Yes
@youngjoon-lee 
Yes
No
> [!WARNING]  

feat(blend): separate unhealthy conn tolerance from malicious tolerance

---

nomos-services/mempool/src/da/service.rs
nomos-services/mempool/src/tx/service.rs

In mempool [refactor] one line was missed which returns MempoolError through reply channel.
In this PR I also added the same error reporting to tx mempool. Because of a new line added to the message handling code - clippy complaints about cognitive complexity - we can either allow it or extract function as done in DA.
Please share you preference and I'll update other pool to match the decision.
A line was missed in a refactor https://github.com/logos-co/nomos/pull/1133/files#diff-d5ae27d19a7f2625f3277f74b24650e441ea8b9ac1e0de0f3fe2cadd15cef25bL395
|@bacv @ntn-x2 
N/A
N/A

fix: Return mempool error when AddItem fails

---

nomos-da/network/core/src/protocols/sampling/behaviour.rs
nomos-da/network/core/src/swarm/common/monitor.rs
nomos-da/network/messages/src/sampling.rs
nomos-services/data-availability/sampling/src/backend/kzgrs.rs
tests/src/topology/configs/da.rs
tests/src/topology/mod.rs

It was observed that even in the perfect network conditions some sampling requests wouldn't be sent. There were couple of cases that were not handled as sampling behavior doesn't necessary start the stream between peers:
- When there is no connection between peers `open_stream` returns `ConnectionReset` io error, sample request fails.
- When a stream is being reused, receiving end already has stopped listening to the stream after the first message - sample request fails.
- UnexpectedEof happens when peer closes the stream and in our case this is expected and shouldn't be propagated as an error.
Since dispersal service now has an option to try sampling before publishing into the mempool, a small change was made in sampling service to ensure that sampling service invalidates only blobs that …

fix(DA): Sampling behaviour lost requests

---

compose.static.yml

Nomos testnet runs `compose.static.yaml` which uses image published to the ghrc.io (https://github.com/logos-co/nomos/pkgs/container/nomos). Update to the repository name also changed the image name.
N/A
N/A
N/A
N/A

chore: Update nomos image to match repository name

---

Dockerfile
ci/Dockerfile
testnet/Dockerfile

This PR updates the installation command for `cargo-binstall` to use `--locked`.
Without `--locked`, Cargo may attempt to resolve newer dependency versions, leading to build failures due to breaking changes in transitive dependencies. Specifically, `h3-quinn v0.0.7` fails to compile due to private field access in quinn::StreamId, causing cargo install cargo-binstall to break.
This does not affect the github action.
Example of failing build when the `cargo-binstall` is not locked.
https://github.com/logos-co/nomos/actions/runs/13925045508/job/38967212800
N/A
N/A
N/A

ci: Use locked dependency versions for cargo binstall

---

nomos-core/risc0_proofs/bundle_balance/Cargo.toml
nomos-core/risc0_proofs/covenant_nop/Cargo.toml
nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml
nomos-core/risc0_proofs/ptx/Cargo.toml

`bytemuck_derive` is risc0 dependency and after a new release it became inccompatible with 1.81.0 rustc toolchain that risc0 uses.
Yes
N/A
N/A
N/A

fix: Use bytemuck_derive 1.8.1 for risc0

---

nomos-utils/src/bounded_duration.rs

Added bounded duration compatibility with `core::time::Duration`. Notice that when using `MinimalBoundedTime` duration serialization defaults to human readable (basically delegates into `time::Duration` serialization). This change may make some current config fail. But on the other hand, it would be easier to handle them. cc: @bacv.
Just added trait implementation so we can deserialize into `core::time::Duration`.
N/A
N/A
N/A

feature: Add bounded duration compatibility for core::time::Duration

---

nomos-services/data-availability/verifier/src/backend/kzgrs.rs
tests/src/nodes/executor.rs
tests/src/nodes/validator.rs
tests/src/tests/da/disperse.rs
tests/src/topology/mod.rs

When dispersing data to a network with more than two subnets, the share wouldn't be included in the block because verification would fail because of fixed domain size in verifier. To fix this, size is now passed from the configuration, test was added but ignored, because it seems that in a network of 4 nodes a longer time is needed to wait until all nodes mark the blob in block. This will be fixed in the future when in integration tests we'll be able to use mempool inspection tools to know when tests can proceed with assertions.
Yes
Yes
No

fix(DA): Pass share verification domain size from the configuration in verifier

---

nomos-sdp/Cargo.toml
nomos-sdp/src/ledger.rs
nomos-sdp/src/lib.rs

Sdp ledger uses provider states to verify the transitions requested through sdp messages. State change is only recorded into the repository when `mark_in_block` is called. How provider information and declarations are added, retrieved or processed afterward is left to handle for the repository implementation. 
Reward request is sent to `RewardsRequestSender` implementer, and it's assumed such implementation would have it's own `mark_in_block` functionality, the comment is added in sdp ledger `mark_in_block` method.
The assumed flow when integrated into the consensus would look something like this:
- Verify block - process each sdp item with `sdp_ledger.process_sdp_message()`
- If any transaction fails - discard block with `sdp_ledger.discard_block()`
- If block looks good (including all …

feature(sdp): Sdp ledger without grabage collection

---

nomos-bundler/Cargo.toml
nomos-bundler/nomos-node/bundle.rs

The compile breaks on the CI because the tauri builder version is automatically updates. The make the code compile and work both locally and on CI, one of the possible solution was to update the version

chore: update tauri builder version to match the CI 

---

nodes/nomos-node/node/src/api/handlers.rs

Minor fix for the block api call docs. The doc listed a call as get, while it is post.

fix(docs): block api call get -> post

---

nodes/nomos-executor/executor/src/api/backend.rs
nodes/nomos-executor/executor/src/api/handlers.rs
nodes/nomos-executor/http-client/src/lib.rs
nomos-cli/src/cmds/executor.rs
nomos-services/api/src/http/da.rs
nomos-services/data-availability/dispersal/src/backend/kzgrs.rs
nomos-services/data-availability/dispersal/src/backend/mod.rs
nomos-services/data-availability/dispersal/src/lib.rs

The disperse call for the da is not returning blob id. This information is useful to track blob ids when interacting with da.
Yes
@pradovic 
Yes
There is a change in da dispersal api return object to include blob id.
> [!WARNING]  

feat(api): return blob id in disperse call

---

nomos-sdp/src/ledger.rs
nomos-sdp/src/lib.rs
nomos-sdp/src/state.rs
nomos-services/sdp/src/adapters/rewards/mod.rs
nomos-services/sdp/src/adapters/services/mod.rs
nomos-services/sdp/src/backends/ledger.rs
nomos-services/sdp/src/lib.rs
tests/src/tests/da/disperse.rs

SDP specification removed Reward and introduced Activity message. Now withdrawal can't claim reward, and in turn it can't declare activity after it already declared the withdrawal (even in the same block).
[Spec](https://www.notion.so/Service-Declaration-Protocol-Specification-17b8f96fb65c80c69c2ef55e22e29506)
@madxor @bacv 
Yes
No

refactor(sdp): Activity message

---

consensus/cryptarchia-engine/src/lib.rs
nomos-services/cryptarchia-consensus/src/lib.rs

WIP. Built on top of https://github.com/logos-co/nomos/pull/1262.
I will add more details if this PR becomes relevant, but for now it suffices to say that I am playing around with returning information about the pruned blocks from cryptarchia. This can be used by the cryptarchia service to then delete those blocks from the persistent storage.
What this PR does not do (yet) is:
1. Conditionally delete old forks only if they have been tested for density, sparing the ones that are old but not long enough (following the current fork choice rule which is undergoing a refactoring)
2. Retrieve missing blocks from storage if not found in memory before triggering backfilling. This is also conditional to the fork choice rule being updated, as old forks might be considered invalid past `k`, …

feat: return pruned block info from cryptarchia engine

---

consensus/cryptarchia-engine/src/lib.rs
nomos-services/cryptarchia-consensus/src/lib.rs

> **PARKED FOR NOW, AS THE FORK-CHOICE RULE IS GETTING UPDATED. THIS WILL BE PICKED UP ONCE WE HAVE A NEW SPECIFICATION FOR THE NEW FORK CHOICE RULE**.
Builds on top of https://github.com/logos-co/nomos/pull/1262.
It integrates the new `prune_forks` function of the cryptarchia consensus engine in two instances: when the node appends a new block to its local canonical chain, or when the node applies a new block and after it applies its own fork-choice rule. The in-memory storage is pruned after any relevant state is stored according to the `StateOperator` logic. This means that the forks are not pruned when the state is being restored or during bootstrapping/recovery processes, but all forks created during those processes will be trimmed as soon as a new block is appended to the canonical …

feat: integrate fork pruning in cryptarchia service

---

.github/workflows/code-check.yml

`self-hosted` label might pickup either linux or macos runner, to run tests on different platforms `linux` label was added when running on self-hosted, for macos jobs the github runner is used.
Yes
@bacv
N/A
N/A

ci: Use linux label for self-hosted runner

---

nomos-libp2p/Cargo.toml
nomos-libp2p/src/swarm.rs
nomos-services/network/src/backends/libp2p/swarm/mod.rs

With the new NAT traversal integration, we confirm external addresses only after they have been verified by the (under development) black box machine, hence we do not add them anymore to kademlia directly (unless there will be an explicit configuration stating so).
Yes.
@ntn-x2 
N/A
No.

feat: do not add external address to kademlia automatically

---

.github/workflows/code-check.yml

The way `github` does string interpolation made it so that the OS array (e.g. `[self-hosted, macOS]`) was printed as its type (e.g. `Array`), which means different OSs were sharing the same cache.
This PR makes it so the string interpolation for arrays prints the values instead of the type (e.g. `self-hosted_macOS`).
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  

fix(ci): Make cache keys independent between runners' OSs.

---

nomos-da/kzgrs-backend/src/encoder.rs

Fixes:
```
--> nomos-da/kzgrs-backend/src/encoder.rs:412:5
|
412 |     #[should_panic]
|     ^^^^^^^^^^^^^^^ help: consider specifying the expected panic: `#[should_panic(expected = /* panic message */)]`
```
cc. @danielSanchezQ This is what I added to my PR, so I removed it to a separate tiny PR

fix: clippy should panic message

---

nomos-services/membership/Cargo.toml
nomos-services/membership/src/backends/mock.rs
nomos-services/membership/src/backends/mod.rs

This PR is a small fix in membership service mock backed. The update method needs to assert that the new finalized block is > then current latest

fix(membership): assert block number and latest block number in update

---

.cargo/config.toml
ledger/nomos-ledger/src/lib.rs
nomos-da/network/core/src/maintenance/balancer.rs
nomos-da/network/core/src/swarm/common/balancer.rs
nomos-da/network/core/src/swarm/common/monitor.rs
nomos-sdp/src/ledger.rs
nomos-services/data-availability/sampling/src/backend/kzgrs.rs
nomos-services/key-management-system/src/backend/preload.rs
nomos-services/time/src/backends/ntp/testutils.rs
rust-toolchain.toml

There are a bunch of rustc lints which are allow-by-default.  The list is presented [here](https://doc.rust-lang.org/beta/rustc/lints/listing/allowed-by-default.html). This PR sets up our `.cargo/config.toml` to list them all explicitly, so  that future PRs can tackle them in batches. As for this PR, we enforce `redundant_imports` (which triggered some warnings) and `redundant_lifetimes` (which did not trigger any warnings).
Unfortunately there is no exhaustive list of groups that contains all allow-by-default lints, hence we need to manually add new lints whenever we upgrade our Rust version, in case new allow-by-default lints have been introduced or stabilised.
Yes.
@ntn-x2 
N/A
No.

chore: setup config for rustc lints

---

.github/workflows/code-check.yml
nodes/nomos-executor/config.yaml
nodes/nomos-executor/executor/src/main.rs
nodes/nomos-node/node/src/main.rs

We add a boolean flag that allows us to dry-run a binary and exit right after the config file is deserialized, to only check for its validity. This can be enabled with the `--check-config` on both binaries. The new capability is integrated into our CI, in the test job, to re-use the binaries that are anyway built for integration tests.
I also tried to add the [`deny_unknown_fields`](https://serde.rs/container-attrs.html#deny_unknown_fields) to the overarching config objects, but it seems they do not work when `flatten` is used, which we do, and it needs further investigation. So right now the checks fail if a field is missing but do not detect if there are unused fields. Worth looking into it in the future.
I also fixed the config files by using the values used in integration tests.
Yes. …

feat: add dry-run capabilities to binaries and add checks in CI

---

consensus/cryptarchia-engine/src/lib.rs
nomos-services/cryptarchia-consensus/src/states.rs
nomos-services/network/src/backends/libp2p/swarm/gossipsub.rs
tests/src/tests/cryptarchia/happy.rs

After investigating the `two_nodes_happy` test for a while, I realised that when the two nodes proposed blocks for the same slot their forks would get immediately pruned off. That'd happen even if the forks were happening from LIB (or genesis). Thus:
- Fix a block pruning condition that was pruning forks older than (and including) selected depth (e.g.: LIB), instead of strictly older.
- Fix flaky behaviour on `two_nodes_happy` test.
Closes: https://github.com/logos-co/nomos/issues/1309 
Closes: https://github.com/logos-co/nomos/issues/1304
Yes
@strinnityk 
N/A
N/A
> [!WARNING]  

fix(cryptarchia): Fix misbehaviour due to pruning condition and flaky `two_nodes_happy` test.

---

.github/workflows/code-check.yml

Remove the CI step that runs `two_nodes_happy`, since the test is run in the main test run, and this specific job does not run any tests anyway, at the moment.
Yes.
@ntn-x2 
N/A
No.

chore(ci): two_nodes_happy is not ignored anymore

---

nodes/nomos-executor/executor/src/lib.rs
nodes/nomos-node/node/src/lib.rs
nomos-services/blend/src/backends/libp2p/mod.rs
nomos-services/blend/src/backends/libp2p/swarm.rs
nomos-services/blend/src/backends/mod.rs
nomos-services/blend/src/lib.rs
nomos-services/blend/src/settings.rs
nomos-services/chain-service/src/blend/adapters/libp2p.rs
nomos-services/chain-service/src/blend/mod.rs
nomos-services/chain-service/src/lib.rs
nomos-services/chain-service/src/relays.rs

This PR changes the interface between the Blend service and the Blend swarm to allow the service to pass a session stream to the swarm. No logic is yet executed upon session change, besides updating the internal membership (which is statically configured at the moment).
The change of `NodeId` from an associated type to a generic was required else we would not be able to create a stream yielding a `Membership<NodeId>` from outside the backend if we don't know the concrete type of `NodeId` in the service. So we need to change the logic for the `NodeId` to be injected all the way down from the node binary, which knows all the concrete types used. 
Yes.
@ntn-x2 
N/A
No.

feat(blend): add support for session clock in blend swarm

---

nomos-utils/Cargo.toml
nomos-utils/src/fisheryates.rs

Refactore fisher yates shuffling algorithm so it is generic over rng instead of using a custom seed over chacha.
Its really simple
N/A
N/A

chore(rand): Refactor fisher yates to be generic over rng

---

nodes/nomos-executor/executor/src/lib.rs
nodes/nomos-node/node/src/lib.rs
nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs
nomos-services/data-availability/network/src/lib.rs
nomos-services/data-availability/sampling/src/lib.rs
nomos-services/data-availability/sampling/src/network/adapters/common.rs
nomos-services/data-availability/sampling/src/network/adapters/executor.rs
nomos-services/data-availability/sampling/src/network/adapters/validator.rs
nomos-services/data-availability/sampling/src/network/mod.rs
nomos-services/data-availability/verifier/src/network/adapters/common.rs
nomos-services/data-availability/verifier/src/network/adapters/executor.rs
nomos-services/data-availability/verifier/src/network/adapters/validator.rs

This PR introduces da-network message and uses it from da-sampling.
Context: https://github.com/logos-co/nomos/pull/1435.

feat(da): use da-network get commitments from sampling 

---

nomos-libp2p/src/behaviour/kademlia/behaviour_ext.rs
nomos-libp2p/src/behaviour/kademlia/swarm_ext.rs
nomos-services/chain-service/Cargo.toml
nomos-services/chain-service/src/network/adapters/libp2p.rs
nomos-services/chain-service/src/network/mod.rs
nomos-services/network/src/backends/libp2p/command.rs
nomos-services/network/src/backends/libp2p/swarm/kademlia.rs
nomos-services/network/src/backends/libp2p/swarm/mod.rs

This PR adds functionality to consensus service network adapter to request downloading missing blocks in order to connect an orphan block with local chain. 
It chooses a random peer from all discovered peers that are not connected, and falls back to connected peers if such peers don’t exist. 
Note: This PR not implementing the actual logic to trigger downloading missing blocks for an orphan block and adding them to the block tree.
Yes. Please also see [Bootstrapping spec](https://www.notion.so/Cryptarchia-v1-Bootstrapping-Synchronization-1fd261aa09df81ac94b5fb6a4eff32a6)
@andrussal 
N/A
N/A

feat(chain): network adapter logic for orphan blocks download

---

Cargo.toml
nomos-core/proof_statements/Cargo.toml
nomos-core/risc0_proofs/Cargo.toml
nomos-core/risc0_proofs/proof_of_leadership/Cargo.toml
nomos-services/tracing/src/lib.rs

Enforce the last lints that make sense to enforce AND are low pain since they do not require big changes. Next, we will start enabling one lint at the time, most likely.
* [clippy::cfg_not_test](https://rust-lang.github.io/rust-clippy/master/index.html#/cfg_not_test): we had one instance. In that case, the tracing crate would anyway panic if called more than once, so it does not hurt to run the initialization function once only, also outside of tests.
* [clippy::dbg_macro](https://rust-lang.github.io/rust-clippy/master/index.html#/dbg_macro): we have debug logs instead. In the past, one of these slipped in the Overwatch crate and was polluting all the logs because there is no way of filtering them. `debug_assert`s can still be used. No affected code.
* …

chore(lints): enforce low-pain rustc and Clippy lints

---

nomos-da/network/core/src/behaviour/executor.rs
nomos-da/network/core/src/behaviour/validator.rs
nomos-da/network/core/src/protocols/sampling/mod.rs
nomos-da/network/core/src/protocols/sampling/requests/mod.rs
nomos-da/network/core/src/protocols/sampling/requests/request_behaviour.rs
nomos-da/network/core/src/protocols/sampling/responses/mod.rs
nomos-da/network/core/src/protocols/sampling/responses/response_behaviour.rs
nomos-da/network/core/src/protocols/sampling/streams.rs

We are splitting sampling behavior into 2 independent behaviors. One for requests and one for responses.
This already remove the limitation of sample replies to external (out of DA network) entities.
This is a previous step for having and extra behavior for historical DA sampling.
It just split and moves things around, then regroup them in a single behavior.
N/A
N/A
> [!WARNING]  

chore(sampling): Split sampling behaviour

---

nomos-services/data-availability/network/src/addressbook.rs
nomos-services/data-availability/network/src/lib.rs
nomos-services/data-availability/network/src/storage/mod.rs

This PR keeps the list of all known latest addresses for all peers in memory. It is a precondition for the https://github.com/logos-co/nomos/pull/1525.

feat(da-network): cumulative in-memory addressbook 

---

nomos-da/network/core/src/protocols/sampling/historic/request_behaviour.rs

Idea for solving the open stream returning connection reset error on dial. Context:https://github.com/logos-co/nomos/pull/1545#discussion_r2283152905

feat(da-network): historic sampling behavior - wait for connection on dial

---

nomos-blend/network/Cargo.toml
nomos-blend/network/src/core/mod.rs
nomos-blend/network/src/core/tests/mod.rs
nomos-blend/network/src/core/tests/utils.rs
nomos-blend/network/src/core/with_core/behaviour/tests/bootstrapping.rs
nomos-blend/network/src/core/with_core/behaviour/tests/connection_maintenance.rs
nomos-blend/network/src/core/with_core/behaviour/tests/message_handling.rs
nomos-blend/network/src/core/with_core/behaviour/tests/utils.rs
nomos-blend/network/src/core/with_edge/behaviour/handler/mod.rs
nomos-blend/network/src/core/with_edge/behaviour/handler/ready_to_receive.rs
nomos-blend/network/src/core/with_edge/behaviour/mod.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/bootstrapping.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/message_handling.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/mod.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/utils.rs

Blend testing PR 2/3 and based on top of the core->core testing one from which it shares most of the test setup infrastructure: https://github.com/logos-co/nomos/pull/1542.
This PR introduces test cases for all the edge cases I could think of, and helped me find a bug that happens when a number of edge peers connect to a core node which would bring the total number of connected peers above the maximum threshold. In some cases, we would still receive and bubble up to the swarm the messages we receive from both of them, although some of the connections should have been rejected. So we have a fix now with a two-step phase: we first upgrade the connection, and then when we are ready to receive we check again, and since libp2p is not multithreaded, we are sure that at any given time we are …

test(blend): add core->edge behavior tests

---

nodes/nomos-executor/config.yaml
nodes/nomos-node/config.yaml
nomos-blend/network/src/core/mod.rs
nomos-blend/network/src/core/tests/utils.rs
nomos-blend/network/src/core/with_core/behaviour/handler/mod.rs
nomos-blend/network/src/core/with_core/behaviour/mod.rs
nomos-blend/network/src/core/with_core/behaviour/tests/utils.rs
nomos-blend/network/src/core/with_edge/behaviour/handler/mod.rs
nomos-blend/network/src/core/with_edge/behaviour/mod.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/bootstrapping.rs
nomos-blend/network/src/core/with_edge/behaviour/tests/utils.rs
nomos-libp2p/src/protocol_name.rs
nomos-services/blend/src/core/backends/libp2p/behaviour.rs
nomos-services/blend/src/core/backends/libp2p/settings.rs
tests/src/topology/configs/blend.rs

It makes the Blend libp2p stack configurable in terms of what protocol name it speaks, but it adds the config to the existing config to make the codebase compile. We want to revise how we set-up a top-level "operation mode" to distinguish among the different deployments.

chore(blend): make Blend protocol name a parameter

---

nomos-services/data-availability/verifier/src/backend/trigger.rs
nomos-services/data-availability/verifier/src/lib.rs

Overwatch service loop is executed in on one thread, no need to lock the list of blob ids for publishing as we can get the exclusive access to it.
Yes
@bacv
N/A
N/A

fix(da): Remove rwlock from mempool publish trigger

---

nodes/nomos-node/node/src/config/blend.rs
nomos-services/blend/src/edge/backends/libp2p/settings.rs
nomos-services/blend/src/edge/backends/libp2p/swarm.rs
nomos-services/blend/src/edge/backends/libp2p/tests/message_handling.rs
nomos-services/blend/src/edge/backends/libp2p/tests/redials.rs
nomos-services/blend/src/edge/backends/libp2p/tests/utils.rs

Fixes https://github.com/logos-co/nomos/issues/1502 (see issue comments for why this PR alone is sufficient to fix the issue). For more context about the meaning of the redundancy parameter, refer to the [Discord thread](https://discord.com/channels/1111286067413405788/1410163003999125524).
The only thing I did not implement in here, because I do not think the gains justify the additional overhead, is to keep track of what peers are being sent each message, so that when a dialing with a peer for a given message fails, we avoid picking up a peer we have already sent the same message to. Nevertheless, since edge nodes are not banned and core nodes simply discard duplicated messages, I do not think it's a big issue. Also, since Blend is not meant to run for sets smaller than 32 elements, the …

feat(blend): introduce redundancy factor for edge nodes

---

.cargo-deny.toml

This PR should fix the CI cargo-deny error. We will ignore tracing-subscriber vulnerability for now

chore(ci): cargo dany ignore tracing subscriber vulnerability

---

nomos-da/network/core/src/protocols/sampling/errors.rs
nomos-da/network/core/src/protocols/sampling/historic/mod.rs
nomos-da/network/core/src/protocols/sampling/historic/request_behaviour.rs
nomos-da/network/core/src/protocols/sampling/mod.rs
nomos-services/data-availability/dispersal/src/adapters/network/libp2p.rs
nomos-services/data-availability/network/src/backends/libp2p/common.rs
nomos-services/data-availability/network/src/backends/libp2p/executor.rs
nomos-services/data-availability/network/src/backends/libp2p/validator.rs

In order to implement historical sampling in sampling service, there was a need to unify the types. 
Also request behavior types were updated to include blob id as it is needed to match light shares and commitments.
After this message in sampling service will be added and logic to sample and verify blobs, and return response to the caller.
Yes.
@pradovic 
Yes
No
> [!WARNING]  

feat(da-network): historic sampling behavior and service glue

---

nomos-core/chain-defs/src/crypto.rs
nomos-core/chain-defs/src/mantle/tx.rs
zk/poseidon2/src/lib.rs

Exports some types for convinience in the poseidon2 crate. Re-export them in the core/crypto module too.
A tiny refactor of types comes with this changes too.
Yes
N/A
N/A
> [!WARNING]  

chore(zk): Re-export poseidon hash types in core

---

nomos-services/membership/Cargo.toml
nomos-services/membership/src/backends/mock.rs

This fixes a membership tests that creates mock provider ids

fix: membership test need to generate eliptic curve for pid

---

nomos-blend/message/src/crypto/proofs/mod.rs
nomos-blend/message/src/crypto/proofs/quota/mod.rs
nomos-blend/message/src/crypto/proofs/selection/inputs.rs
nomos-blend/message/src/crypto/proofs/selection/mod.rs
nomos-blend/message/src/crypto/proofs/selection/serde.rs
nomos-blend/message/src/encap/encapsulated.rs
nomos-blend/message/src/encap/mod.rs
nomos-blend/message/src/encap/tests.rs
nomos-blend/message/src/encap/unwrapped.rs
nomos-blend/message/src/message/blending_header.rs

PR built on top of https://github.com/logos-co/nomos/pull/1691. It mirrors the same API as for PoQ, integrating the necessary inputs in the message decapsulation process.
Next PR will try to make the code compile for the remaining of the Blend core crates.
Yes.
@ntn-x2 @madxor @youngjoon-lee 
Yes. There is a missing detail explaining how to convert `Fr` to bytes for hashing in the PoSel, but I opened a comment which will most likely be addressed soon: https://www.notion.so/Blend-Protocol-215261aa09df81ae8857d71066a80084?d=26b261aa09df80198a78001c9e617d18&source=copy_link#215261aa09df819991e6f9455ff7ec92.
See https://www.notion.so/Blend-Protocol-215261aa09df81ae8857d71066a80084?d=26b261aa09df80198a78001c9e617d18&source=copy_link#215261aa09df819991e6f9455ff7ec92.

feat(blend): introduce PoSel

---

nomos-services/chain/chain-leader/src/lib.rs
nomos-services/chain/chain-service/src/lib.rs
nomos-services/wallet/Cargo.toml
nomos-services/wallet/src/lib.rs
testnet/cfgsync/src/config.rs
tests/src/nodes/validator.rs
tests/src/tests/cryptarchia/bootstrap.rs
tests/src/topology/configs/bootstrap.rs
tests/src/topology/configs/mod.rs
tests/src/topology/mod.rs

Closes #1656 
This PR makes the chain service mark itself as ready only after it has fully completed bootstrapping (**IBD + ProlongedBootstrapPeriod**).
In other words, the chain service becomes ready only after **IBD** is done and Cryptarchia switches to **Online**. 
We made this decision so that other services become operational only after the **LIB** is available.
There are currently 3 services that explicitly wait until the chain service becomes ready.
- chain-leader
- wallet
- It wasn't calling `wait_until_services_are_ready`. This PR adds it.
- api
- But we may want this service to begin its job earlier even before the chain is ready. I didn’t do it in this PR, as it's not urgent and requires other fixes alongside. If we need it, we can do it nicely by the refactoring that I …

feat(chain): mark the service as ready after bootstrapping is done

---

nomos-da/network/core/src/protocols/sampling/errors.rs
nomos-da/network/core/src/protocols/sampling/historic/mod.rs
nomos-da/network/core/src/protocols/sampling/historic/request_behaviour.rs
nomos-da/network/core/src/protocols/sampling/mod.rs
nomos-da/network/core/src/protocols/sampling/opinions.rs
nomos-da/network/core/src/protocols/sampling/requests/request_behaviour.rs
nomos-da/network/core/src/swarm/validator.rs
nomos-services/data-availability/network/src/backends/libp2p/common.rs

This PR implements opinions tracking in historic sampling behavior. It is implemented in the similar fashion as regular sampling, only that in this case it was easier to bulk opinions and form single event per sampling. This is why opinion enum was expanded to hold vec of events instead of single one.
This is one of PRs related to da sampling opinions. Previous one is: https://github.com/logos-co/nomos/pull/1717.
Yes.
@pradovic 
Yes
No
> [!WARNING]  

feat(da-network): historic sampling opinions

---

.github/CODEOWNERS

Added myself as codeowner in the folders that may locke PRs.
N/A
N/A
N/A
N/A
> [!WARNING]  

chore(codeowners): Add third codeowner to avoid pr locking
